### ISSUE TITLE
Local development - webhooks

### ISSUE THREAD

**Issue by AuHau** [anymail/django-anymail#102]
Hey there,

I am wondering if there is any easy way how to use Anymail during local development?
I know about the Test backend, and generally I know for sending emails you can use some other backend, so the sending out emails is not the main part I am asking for. What I am wondering more is about testing the inbound webhooks, where it is bit cumbersome handling all the security related stuff.

Right now, I am doing bit monkey-patching to ease my development, but yeah it is not the best thing to do, so I am wondering - is there some better way?

What I am doing now:
```
if DEBUG:
    def no_validation(*args, **kwargs):
        pass

    MailgunBaseWebhookView.validate_request = no_validation
    AnymailBaseWebhookView.validate_request = no_validation
```

**Comment by medmunds** [comment]
It sounds like you have some tests that call `self.client.post("/anymail/mailgun/inbound/", ...)`, right?

What you're doing now is fine. You could simplify by just patching `AnymailBaseWebhookView.run_validators`, which covers all validations for all Anymail webhooks. (And if you're not already familiar with it, you might want to check out [unittest.mock](https://docs.python.org/3/library/unittest.mock.html)—particularly its `patch` decorator.)

But if your real goal is to test how your inbound signal receiver deals with various inbound messages, it might be easier to just generate inbound events directly:

```python
from django.test import TestCase
from anymail.inbound import AnymailInboundMessage
from anymail.signals import AnymailInboundEvent, inbound

from myapp.models import Comment

class InboundTests(TestCase):
    def test_inbound_messages_become_comments(self):
        # simulate an inbound message (add whatever data you need)
        message = AnymailInboundMessage.construct(
            from_email="user@example.org", to="myapp@example.com", text="help!")
        event = AnymailInboundEvent(
            type="inbound", message=message, event_id="12345")

        # send Anymail's inbound signal -- should invoke your receiver
        # (or just import and call your receiver function directly)
        inbound.send(sender="<probably unused>", event=event, esp_name="Testing")

        # verify your inbound receiver did what you wanted, e.g.:
        self.assertEqual(Comment.objects.count(), 1)
        self.assertEqual(Comment.objects.all()[0].commenter_email, "user@example.org")
        self.assertEqual(Comment.objects.all()[0].content, "help!")
```

One advantage of this approach is it's portable between ESPs. If you ever need to switch from Mailgun, you won't have to rebuild all your test input to match the new ESP's webhook format. (It's also a lot cleaner than trying to build a Mailgun webhook payload by hand.)

AnymailInboundMessage has several class methods for [constructing messages and attachments](https://github.com/anymail/django-anymail/blob/master/anymail/inbound.py#L194) from various kinds of data, which can simplify simulating whatever inbound mail you need for testing.

On the other hand, if your goal is integration- or regression-testing the actual webhooks (say, you've captured a library of raw Mailgun webhook payloads), then posting to Anymail's webhook url like you're doing now makes more sense. If you want a true integration test with validation enabled, you could re-sign the payloads with your testenv's API key by borrowing [`mailgun_sign`](https://github.com/anymail/django-anymail/blob/v2.0/tests/test_mailgun_webhooks.py#L19-L27) from Anymail's webhook test code.

**Comment by AuHau** [comment]
Thanks for the reply!

Well currently I am not even writing any sort of tests, I would like just simply to invoke the inbound signal receiver with different kind of messages as simply as possible... 

Originally I thought that I will just send the payload to the inbound webhook, but as there is lot of security evolved it would heavily slow down the iteration of different payloads, so that is why I did the patching... 

The idea of directly invoking the event is interesting, but as I do not atm plan to write tests for this app (I know bad practice :-D ) it is bit cumbersome...

I guess this is as best as it gets. I understand that most probably you would not like to introduce any "un-secure" setting for local development as it might be easily forgotten for live environments. Maybe it could be mentioned somewhere in documentation that this is easy way for local invocation...

I will close this issue as there is I think nothing else to cover here :-)

**Comment by medmunds** [comment]
Yeah, considering the kinds of things apps tend to do with inbound email, I don't really want to have a setting that disables webhook validation. It'd be too easy for people to unintentionally introduce really serious vulnerabilities in their apps.

It sounds like you have a very specific use case in mind. (Iterating through enough payloads that the validation overhead is an issue, in a debug environment, but not in the context of tests. Fuzzing?)

If monkey-patching feels wrong, another (fully supported, non-brittle) approach is to subclass Anymail's webhook views and override anything you want. You could add your own setting to skip security checks:

```python
from anymail.webhooks.mailgun import MailgunInboundWebhookView

class SecurityOptionalInboundView(MailgunInboundWebhookView):
    def run_validators(self):
        if settings.DANGEROUSLY_SKIP_WEBHOOK_VALIDATION:
            pass  # (or maybe throw an error in production)
        else:
            super(SecurityOptionalInboundView, self).run_validators()
```

Then in your urls.py, hook up your customized view rather than including Anymail's urls.

**Comment by AuHau** [comment]
Yeah, I understand that.

After thinking a bit, I think that the monkey-patching approach is the easiest one, which is what matter most to me atm. 

Thanks for your help!
