### ISSUE TITLE
TLS version for Mandrill

### ISSUE THREAD

**Issue by alex1vanchik** [anymail/django-anymail#105]
Hi guys! Recently received such a letter from MailChimp(Mandrill).
<img width="681" alt="skarmavbild 2018-05-14 kl 09 21 20" src="https://user-images.githubusercontent.com/28433163/39992021-1351ff12-577a-11e8-9e78-211620d50818.png">
We use django-anymail for mailing. Unfortunately could not find the answers to the questions in the anymail documentation or link on the community chat/forum. 
Therefore, we have such questions:
1. Do anymail support TLS 1.2 for Mandrill?
2. If not, Are you going to update the library before May 31, or should we start looking for another solution?

**Comment by medmunds** [comment]
Anymail uses the [Python Requests](http://docs.python-requests.org/en/master/) package for communication with most ESPs, including Mandrill. There's no code in Anymail specific to TLS versions. I believe Requests uses the best version of TLS available to Python (and supported by the remote server), and TLS 1.2 is available in any reasonably-up-to-date configuration.

So if you're seeing API calls using TLS 1.0 or 1.1, the most likely cause is an outdated Python and/or OpenSSL on your system. Look for "to check your Python interpreter's TLS version" in [this post](http://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html). Assuming that's the problem, upgrading Python and OpenSSL should solve it—or look for "python TLS 1.2 *your-platform*" in your favorite search engine. (If you're running Python older than 2.7.9, you should *definitely* upgrade for lots of related reasons.)

If that doesn't help, we'd need to know what OS and version, what Python version, what OpenSSL version, and what version of Requests you have installed.

**Comment by alex1vanchik** [comment]
Thanks for the quick response. We use the latest versions of Python and OpenSSL. The question can be closed
