### ISSUE TITLE
Support new Mailgun webhooks

### ISSUE THREAD

**Issue by medmunds** [anymail/django-anymail#117]
Mailgun has [recently introduced](https://www.mailgun.com/blog/same-api-new-tricks-get-event-notifications-just-in-time-with-webhooks) a new set of tracking webhooks, and has renamed the previous tracking webhooks as "legacy".

Anymail should update to support Mailgun's new webhooks. (Until then, you'll need to choose the "legacy" option when configuring webhooks in the Mailgun control panel.)

For backwards compatibility, Anymail should continue to also accept the legacy webhook payload format.

The [new webhook payloads](https://documentation.mailgun.com/en/latest/user_manual.html#webhooks) use the same [data structure](https://documentation.mailgun.com/en/latest/api-events.html#event-structure) as Mailgun's event polling API, which should eliminate a lot of the oddities around the [legacy payloads](https://documentation.mailgun.com/en/latest/api-webhooks-deprecated.html#webhooks-parameters) (in particular, the complex logic to separate user metadata from Mailgun webhook data). Although the new payloads use the same `event` names as the legacy ones, the new payloads have separate `signature` and `event-data` sections, which can be used to differentiate. (The legacy payloads mix signature and token in at the payload root with other event parameters.)

**Comment by volodchenkov** [comment]
+

**Comment by medmunds** [comment]
Released in Anymail v4.0.
