### ISSUE TITLE
ALLOWED_HOSTS setting

### ISSUE THREAD

**Issue by eriktelepovsky** [anymail/django-anymail#124]
Hi. Can you help me? What should I set into ALLOWED_HOSTS Django setting to support mailgun webhooks, please? Any help is appreciated. Thank you.

**Comment by eriktelepovsky** [comment]
Problem solved, you can close this issue. Thanks.

**Comment by medmunds** [comment]
(For anyone with a similar problem who finds this via search: Anymail doesn't require any special Django ALLOWED_HOSTS setting. But the webhook URL you provide your ESP needs to use the same hostname as your deployed Django app.)
