### ISSUE TITLE
Mailgun silently discards attachments without filenames

### ISSUE THREAD

**Issue by medmunds** [anymail/django-anymail#128]
If you send an attachment without a filename, Mailgun will silently ignore it. The message gets sent, but without that attachment.

Anymail's Mailgun EmailBackend should raise an `AnymailUnsupportedFeature` exception if it detects an attachment without a filename. (Really, Mailgun's API should warn about this case, but because it doesn't, and because the behavior is unexpected and difficult to track down, Anymail should prevent it.)

[Originally reported by @costela in [#125 comment](https://github.com/anymail/django-anymail/issues/125#issuecomment-427500525).]

**Comment by costela** [comment]
FYI: we opened a support issue with Mailgun earlier. I'll report back here as soon as I have a statement from them about this behavior.

**Comment by costela** [comment]
Mailgun's response was basically "not our problem; create a feature request" :/
Opened it here: https://mailgun.uservoice.com/forums/156243-feature-requests/suggestions/35668606-do-not-silently-drop-nameless-attachments-over-htt

**Comment by medmunds** [comment]
Fix released in Anymail v4.3.
