### ISSUE TITLE
Mailgun inbound missing attachments with "store" action

### ISSUE THREAD

**Issue by madisvain** [anymail/django-anymail#132]
* Anymail version - 5
* ESP - Mailgun

I'm getting some email webhooks from Mailgun with a *attachment* POST parameter that contains the JSON for attachment data like this:
```json
[
    {
        "url": "https://storage.eu.mailgun.net/v3/domains/mailgun.upcount.app/messages/eyJwIjpmYWxzZSwiayI6ImE3ZGI0M2Q3LTk0M1QtNDkxNi04N2YwLThiZjAzNDFhZmJmZSIsInMiOiI4ZDUwM2U3ZjU4IiwiYyI6InRhbmtiIn0=/attachments/0",
        "content-type": "application/pdf",
        "name": "Hetzner_2018-12-19_R0008961359.pdf",
        "size": 59121
    }
]
```

So the content is downloadable but the *attachment-count* is missing and the FILES content also.

I'm using Mailgun EU if this makes a difference. Has anybody else had this issue come up - I'm making a fix for this in the MailgunInboundWebhookView. If somebody else has this issue I can make a pull request.

**Comment by erikdrums** [comment]
Same happened to me. It's really easy to miss the point that you have to use forwarding and not storing. Ready your comment probably saved me a ton of debugging. Thanks!

https://anymail.readthedocs.io/en/stable/esps/mailgun/#inbound-webhook.

**Comment by medmunds** [comment]
I'm going to look into whether Anymail can detect this case and issue a specific, helpful error message (like it tries to for some other common configuration errors).

There's also a possibility Anymail's inbound webhook could just support Mailgun's "store" action. Unfortunately, I don't have any way to test that. (As an open source project without any funding, Anymail can't afford the $420/year Mailgun now charges for a plan that supports receiving mail. If anyone from Mailgun sees this and could enable receiving on the account we use for Anymail development/testing, please get in touch.)

**Comment by erikdrums** [comment]
@medmunds Thanks so much for this excellent library and super docs! A helpful error message or support for the "store" action would be great. 
I think even a more explicit wording would do it.
I read the two examples not as the only solutions but just examples of forward().
store() works except for not passing on attachments.

- If you are looking for a simple solution, maybe just mention in the docs that only forward() is supports attachments.

Thanks again!

**Comment by medmunds** [comment]
@erikdrums good idea, that's much simpler. Docs updated.
