### ISSUE TITLE
Fetch body of sent message

### ISSUE THREAD

**Issue by cycleconfident** [anymail/django-anymail#136]
Is there a way to get the (both HTML and text) body of a sent message using Anymail?

So, for example, if I send a batch of emails with a template that includes a tag for the recipient's name, how do I then get hold of the rendered HTML for each recipient?

I'm using Postmark and I know their API has a "message details" endpoint that can be used but in order to use it, is the only way for me to code that separately? Anymail can't do this for me?

**Comment by medmunds** [comment]
Anymail doesn't have this built in. Several ESPs simply don't allow retrieving a message's body after you've sent it. If your code depends on this, you'll be limiting your ability to change ESPs in the future. (A portable alternative is to generate your own message bodies [using Django templating](https://anymail.readthedocs.io/en/stable/tips/django_templates/)—then you have the bodies before you even send the message.)

As you noticed, Postmark *does* allow retrieving sent message bodies in its [outbound message details](https://postmarkapp.com/developer/api/messages-api#outbound-message-details) API. It should be pretty simple to call it. The message id you need is in [`message.anymail_status.recipients`](https://anymail.readthedocs.io/en/stable/sending/anymail_additions/#anymail.message.AnymailStatus.recipients) after sending. And the [requests](http://docs.python-requests.org/en/master/) package (installed with Anymail) makes basic HTTP calls easy. You could do something like:

```python
import requests
from django.conf import settings

def get_sent_message_bodies(message, recipient_email):
    """Returns (text_body, html_body) for a message sent through Postmark using Anymail"""
    # Get ESP's message id for this recipient...
    try:
        message_id = message.anymail_status.recipients[recipient_email].message_id
    except AttributeError:
        raise ValueError("Message has not been sent yet (or wasn't sent with Anymail)")
    except KeyError:
        raise ValueError("Recipient %r not found in %s" 
                         % (recipient_email, message.anymail_status.recipients.keys()))

    # Call Postmark's outbound-message-details API...
    response = requests.get(
        "https://api.postmarkapp.com/messages/outbound/{}/details".format(message_id),
        headers={"X-Postmark-Server-Token": settings.ANYMAIL["POSTMARK_SERVER_TOKEN"],
                 "Accept": "application/json"})
    response.raise_for_status()  # handles API errors
    details = response.json()
    return (details["TextBody"], details["HtmlBody"])
```

(There are also a few [Python Postmark API](https://postmarkapp.com/developer/integration/community-libraries#python) packages if you don't want to use requests directly. Either way, though, if you ever changed ESPs, you'd need to rework the second half of that function.)

**Comment by cycleconfident** [comment]
Ah, OK - thanks @medmunds.

I think I'll use Django templates to do this bespoke email content creation then - that way, I won't be depending on using Postmark forever more.
