### ISSUE TITLE
Per-recipient message content using batch send

### ISSUE THREAD

**Issue by cycleconfident** [anymail/django-anymail#138]
According to the Postmark API docs, each recipient in a batch send (not using ESP templates) can contain it's own message content. I have also confirmed this with them over email.

The relevant API call is https://postmarkapp.com/developer/api/email-api#send-batch-emails

When using Anymail, I can't see any way of using this functionality. Is the only way to not use batch send and send separate messages? I don't really want to use ESP templates either, to be honest.

**Comment by cycleconfident** [comment]
OK, that all makes sense. Thanks.

My initial reason for using the batch email API was in order to send emails to a (fairly) large list of users and be able to track who had received them and read them etc.

However, I'm now using the message metadata to connect tracking signals from PM to my stored email objects so I may well not need to use that API any more and can send separate messages instead, all linked to the one stored email object.

Interesting, thanks for your feedback.

**Comment by medmunds** [comment]
Sounds good. I'm going to close this issue then, but happy to answer any other questions you might have.

Incidentally, you might want to check out Anymail's `message_id`, which is intended specifically for matching up [tracking events](https://anymail.readthedocs.io/en/stable/sending/tracking/#anymail.signals.AnymailTrackingEvent.message_id) with [sent messages](https://anymail.readthedocs.io/en/stable/sending/anymail_additions/#anymail.message.AnymailStatus.message_id).
