### ISSUE TITLE
Sender address rejected when sending to certain domain with Mailgun

### ISSUE THREAD

**Issue by OmenApps** [anymail/django-anymail#143]
I'm having problems sending mail to certain domains via Mailgun with Anymail. Email to xxx@gmail.com and a most other domains goes through with no problem, but email to xxx@icloud.com fails.

Anymail: Latest stable release
ESP: Mailgun
Django: 2.1

My settings:

```
INSTALLED_APPS += ['anymail']
EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
ANYMAIL = {
    'MAILGUN_API_KEY': env('MAILGUN_API_KEY'),
    'MAILGUN_SENDER_DOMAIN': env('MAILGUN_SENDER_DOMAIN'),
}

```

here, config.BASE_DOMAIN is 'myappdomain.com'

Below is the basic code I'm using to send email. In this example, I replaced the subject and content variables with strings for simplicity. We use a dedicated Mailgun sender domain, mg.myappdomain.com

```
msg = EmailMultiAlternatives('subject', 'txt_content',
                                         'contact@' + config.BASE_DOMAIN, [email])
            msg.envelope_sender = 'contact@mg.' + config.BASE_DOMAIN
            msg.attach_alternative('html_content', "text/html")
            msg.send()
```

The initial message in Mailgun logs is: Accepted: postmaster@mg.myappdomain.com → to_email_addy@icloud.com 'Password Reset E-mail'

But immediately afterward, I get: Will retry in 600 seconds: postmaster@mg.myappdomain.com → to_email_addy@icloud.com 'Password Reset E-mail' Server response: 450 4.1.8 <bounce+98e0eb.0a48d9-to_email_addy=icloud.com@mg.myappdomain.com>: Sender address rejected: Domain not found

```
{
    "severity": "temporary",
    "tags": [],
    "storage": {
        "url": "https://se.api.mailgun.net/v3/domains/mg.myappdomain.com/messages/eRJwIjpmYWxzZSwiayI6ImI1MTY0N2M4LTcyMDjYNDU3Zi05ZTRkLWIwNGUwYzc0NmVkOCIsInMiOiJhZTkxXGI3YjcyIiwiYyI6InRhbmtiIn0=",
        "key": "eyJwIjpmYWxzZSwigPI6ImI1MTY0N2M4LTcyMDgtNDU3Zi05ZTRkLWI07GUwYzc0NmVkOCIsInMiOiJhZTkxZGI3YjcyIiwiYyI6InRhbntiIn0="
    },
    "delivery-status": {
        "tls": true,
        "mx-host": "mx5.mail.icloud.com",
        "code": 450,
        "description": "",
        "session-seconds": 0.6950631141662598,
        "retry-seconds": 600,
        "attempt-no": 1,
        "message": "4.1.8 <bounce+98e0eb.0a48d9-to_email_addy=icloud.com@mg.myappdomain.com>: Sender address rejected: Domain not found",
        "certificate-verified": true
    },
    "recipient-domain": "icloud.com",
    "id": "BtuPartKTRe50Ogyl2YrvB",
    "campaigns": [],
    "reason": "generic",
    "user-variables": {},
    "flags": {
        "is-routed": false,
        "is-authenticated": true,
        "is-system-test": false,
        "is-test-mode": false
    },
    "log-level": "warn",
    "timestamp": 1549685430.744174,
    "envelope": {
        "transport": "smtp",
        "sender": "postmaster@mg.myappdomain.com",
        "sending-ip": "198.61.254.4",
        "targets": "to_email_addy@icloud.com"
    },
    "message": {
        "headers": {
            "to": "to_email_addy@icloud.com",
            "message-id": "20190209041019.1.D590260BF5E2D047@mg.myappdomain.com",
            "from": "contact@myappdomain.com",
            "subject": "Password Reset E-mail"
        },
        "attachments": [],
        "size": 1556
    },
    "recipient": "to_email_addy@icloud.com",
    "event": "failed"
}
```

I contacted Mailgun support, and this is their reply:

> Thank you for contacting Mailgun support.
> 
> It appears that messages are failing due to A DMARC issue. The from addresses on your messages: "to_email_addy@myappdomain.com", do not match with the sending domain of "mg.myappdomain.com".  To resolve this when creating your sending messages verify that the from address matche the sending domain. Please feel free to reach out to us should you require any further assistance.

Any guidance would be appreciated. I read through the directions on the Mailgun section of Anymail docs, and have researched elsewhere as well, but no mater what I do, email to this domain fails. I have tried various combinations of using msg.envelope_sender directly and also using MAILGUN_SENDER_DOMAIN in my settings, but nothing seems to work.

**Comment by medmunds** [comment]
Assuming that `env('MAILGUN_SENDER_DOMAIN')` is the same as `'mg.' + config.BASE_DOMAIN`,  then setting MAILGUN_SENDER_DOMAIN in your settings as you are should be sufficient, and there's no need to use `msg.envelope_sender`. But what you've described doesn't really sound like an Anymail (or even Mailgun) issue.

The SMTP response "4.1.8 <bounce+98e0eb.0a48d9-to_email_addy=icloud.com @mg.myappdomain.com>: *Sender address rejected: Domain not found*" seems to be icloud.com saying, "Hey, you claim to be sending me mail from (mg.)myappdomain.com, but as far as I can tell, that domain doesn't exist."

So the obvious question is why icloud can't find that domain. It's possible you have some DNS configuration issues on mg.myappdomain.com, myappdomain.com, or (since MG support mentioned DMARC) _dmarc.myappdomain.com, specifically around the records used to implement DKIM, SPF, and DMARC. Without knowing your actual domain, it's hard to be more helpful.

It's a little surprising that icloud would block a message that Gmail isn't. You might pull up "Show Original" in Gmail on one of your messages that made it through, and take a look at Google's Authentication-Results header to see if they detected some problems but let the message through anyway. You could also try plugging your actual info into some of the lookup and validation tools listed at [dmarc.org](https://dmarc.org/resources/deployment-tools/) to see if they catch any problems.

**Comment by medmunds** [comment]
@OmenApps I'm going to close this, as it seems unlikely that it's an Anymail issue. 

If my earlier response didn't point you in the right direction, I'd be happy to help you investigate further. But I'd need to know the actual domain you're trying to send from (to check DMARC records), and any other information you've gathered (such as Authentication-Results for a message that was received successfully in Gmail).

**Comment by medmunds** [comment]
@OmenApps one more thought: your message is going out with `"sender": "postmaster@mg.myappdomain.com"`. Some ISPs will verify that the sending address can actually receive email, as an anti-spam measure. (So iCloud might, and Gmail doesn't, perhaps.)

Check that you have an MX (inbound email) record set up for *mg*.myappdomain.com (`dig -t MX mg.myappdomain.com`). If those don't exist and point to Mailgun, look for the MX info in [Mailgun's instructions](https://help.mailgun.com/hc/en-us/articles/202052074-How-do-I-verify-my-domain-).

Also, if that *is* the problem, you might want to double-check that you haven't accidentally added Mailgun's MX into your main myappdomain.com (`dig -t MX myappdomain.com`). If you mix Mailgun and your regular email service, you're essentially saying that your inbound email (for *anyone*@myappdomain.com) can go to *either* your regular email service or Mailgun. That will probably result in lost inbound email. See Mailgun's [Can I use the same domain name for Mailgun and for another email server?](https://help.mailgun.com/hc/en-us/articles/203357040-Can-I-use-the-same-domain-name-for-Mailgun-and-for-Google-Apps-or-another-email-server-) 

Let me know if that solved it.

**Comment by imsrepository** [comment]
God bless the community :)  Adding the MX record solved our issue for the icloud.com domain. Thanks @medmunds
