### ISSUE TITLE
AnymailRequestsAPIError with Mailgun API response 200 "Mailgun Magnificent API"

### ISSUE THREAD

**Issue by chiragchamoli** [anymail/django-anymail#144]
Reporting an error? It's helpful to know:

* Anymail version: 5.0
* ESP : Mailgun
* Versions of Django 2.1.7
* Exact error message and/or stack trace

AnymailRequestsAPIError at /emails/
Invalid JSON in Mailgun API response
Sending a message to chirax@gmail.com from dev.team@xxxx.com
Mailgun API response 200: OK Mailgun Magnificent API

Exception Value: Invalid JSON in Mailgun API response
Sending a message to chirax@gmail.com from dev.team@xxxx.com
Mailgun API response 200: OK Mailgun Magnificent API

Anymail is throwing an exception, but mailgun is sending 200

**Comment by medmunds** [comment]
The problem that Anymail is reporting is *Invalid JSON in Mailgun API response*. 

Although Mailgun is returning a 200 response, the content they are returning—*"Mailgun Magnificent API"*—is not valid JSON. The content of their 200 response needs to be something like the [sample response in Mailgun's docs](https://documentation.mailgun.com/en/latest/api-sending.html#examples). Anymail parses the sent `message_id` from this response.

"Mailgun Magnificent API" is a pretty specific (and weird) API response. Googling it, I see several people have run into this problem using other libraries, but no definitive cause. (But everyone who sees that response agrees the email doesn't actually get sent.)

I'd suggest:
* Double-checking that you've set the correct MAILGUN_API_KEY in your Anymail settings
* Make sure that "xxxx.com" (in `from dev.team@xxxx.com`) is a valid domain in your Mailgun account (or that you've set MAILGUN_SENDER_DOMAIN properly in your Anymail settings)
* Check your [Mailgun API logs](https://app.mailgun.com/app/logs/), and look for an "Accepted" event for that message to see if there's any other helpful info
* If none of that reveals a cause, contact Mailgun support and ask them what their API is trying to tell you when it responds "Mailgun Magnificent API"

Please let us know what you find out. I'd like to add some specific error handling to help the next person who runs into this.

**Comment by medmunds** [comment]
(I opened a ticket with Mailgun support to try to get more info on "Mailgun Magnificent API". But you should still follow the other troubleshooting suggestions above.)

**Comment by medmunds** [comment]
@chiragchamoli Mailgun got back to me right away! The most likely cause is that you've either set MAILGUN_SENDER_DOMAIN to something invalid, or that the From address has an invalid domain name. 

In particular `/` slash characters can't be used in domain names. Here's an example of an incorrect setting that will cause this problem:
```python
ANYMAIL = {
    "MAILGUN_SENDER_DOMAIN": "mail.example.com/myapp",  # NOT VALID
}
```

Could you share the actual, exact `from_email` address and MAILGUN_SENDER_DOMAIN setting you're using? (If you don't want to make them public, you could email me at medmunds@gmail.com.) I want to make sure there's not some valid sender domain that Anymail isn't handling properly.

**Comment by chiragchamoli** [comment]
@medmunds I've set  MAILGUN_SENDER_DOMAIN correctly as you have noted just subdomain. Let me try and debug with your suggestion and report back.

**Comment by medmunds** [comment]
@chiragchamoli thanks for following up. BTW, the message's `envelope_sender` can also affect this (and overrides your MAILGUN_SENDER_DOMAIN setting).

One more suggestion: there's an undocumented Anymail debug setting that will dump the raw API request and response when you send:

```python
ANYMAIL = {
    # ... other settings ...
    "DEBUG_API_REQUESTS": True,  # don't leave this enabled in production
}
```

If you set this and then send a message, the output should include something like:
```text
===== Anymail API request
POST https://api.mailgun.net/v3/_____/messages
...
```

I'm specifically interested in the `_____` part of the POST url. It should be (only) your sender domain. If it includes other stuff, that's the problem. I know that slashes can cause trouble, but if there are other characters that cause the same weird behavior, that would be great to know.

Thanks for investigating.

**Comment by medmunds** [comment]
Aha. Found a couple of other MAILGUN_SENDER_DOMAIN characters that will cause "Mailgun Magnificent API: `#` and `?`.

If you're using .env files, it's pretty easy to get a `#` into your MAILGUN_SENDER_DOMAIN setting:

```python
# settings.py ...
ANYMAIL = {
    'MAILGUN_SENDER_DOMAIN': env('MAILGUN_SENDER_DOMAIN'),
}
```

```bash
# .env ...
MAILGUN_SENDER_DOMAIN=mg.example.com # comment
```

Many dotenv parsers don't support end-of-line comments, so this actually results in your `MAILGUN_SENDER_DOMAIN` being set to `'mg.example.com # comment'`. And then you'll get the cryptic Magnificent API response.

The [change](https://github.com/anymail/django-anymail/commit/412a1b78c66bf67c7cf7c5e916fc134cdd8b785a) I made yesterday will avoid the confusing failure. Instead, you'll get a more-helpful 404 error from Mailgun: `"Domain not found: mg.example.com # comment"`.

**Comment by chiragchamoli** [comment]
Thanks @medmunds . Closing this.

**Comment by medmunds** [comment]
Improved error handling released in Anymail v6.0.

**Comment by jonathan-s** [comment]
I found `DEBUG_API_REQUESTS` here. Grateful for that. It helped me debug an issue with the api. I think it would be great if this were to be documented as well. I see that it's currently undocumented.

**Comment by medmunds** [comment]
@jonathan-s thanks for the suggestion. Just added docs for `DEBUG_API_REQUESTS`.
