### ISSUE TITLE
Randomly msg.anymail_status.message_id is set when sending to single recipient

### ISSUE THREAD

**Issue by justmobilize** [anymail/django-anymail#146]
Reporting an error? It's helpful to know:

Using:
- Python 3.6.7
- Django==1.11.2
- django-anymail==5.0
- requests==2.21.0
- Postmark
- EMAIL_BACKEND = 'anymail.backends.postmark.EmailBackend'
- ANYMAIL = {'POSTMARK_SERVER_TOKEN': 'xxxxxxxxxxxxxxxx'}

We send all of our emails to a single recipient, but sometimes `msg.anymail_status.message_id` is a set, looking at code it seams that should only happen if there are multiple recipients

Any thoughts to why this might happen?

**Comment by medmunds** [comment]
You could find out why Anymail thinks there are multiple recipient emails involved by looking at [`msg.anymail_status.recipients`][recipient_status]. Each item in that dict maps a recipient email address (dict key) to an individual status and message_id.

One possibility: Anymail 5.0 had some bugs with how it interpreted Postmark responses if the recipient email used mixed case. Postmark always reports failures using lowercase, so if you were sending to an email like `NoSpamPlease@example.com` you could end up with separate `anymail_status.recipients` entries for both that and the lowercase `nospamplease@example.com`. In Anymail 6.0, this is fixed, and you'll get a single status for the capitalization you sent with (assuming a single To recipient and no Cc or Bcc).

Another way this could happen is if you're unintentionally including multiple email addresses in a single "to" field. (E.g., if you're using user-supplied data for the To email and users can include a comma in that data.)

In any case, taking a look at the `recipients` dict should provide more info. It might also help to check your Postmark [server activity] log: check the Processed event to see if there are actually multiple recipients listed.

Please let me know what you find out.

[recipient_status]: https://anymail.readthedocs.io/en/stable/sending/anymail_additions/#anymail.message.AnymailStatus.recipients
[server activity]: https://account.postmarkapp.com/servers/

**Comment by justmobilize** [comment]
@medmunds thanks!

For the reply! So one is definitely a mixed case issue, So I can update and fix that.

Our code is pretty specific, so I know there is only 1 to and nothing else. It's super random and no way for me to catch anything on `msg.anymail_status.recipients`.

**Comment by medmunds** [comment]
@justmobilize sounds like updating to the latest Anymail will solve this for you. If that works, please mark this closed.

If not, and you're still seeing a problem, I'd suggest adding some code to log more info when the problem occurs. E.g.:
```python
    msg.send()
    if isinstance(msg.anymail_status.message_id, set):
        # Capture the recipients in error log/Sentry:
        raise ValueError('Multiple recipients: %r' % msg.anymail_status.recipients.keys())
    # else msg.anymail_status.message_id will be a single str or None
```

**Comment by justmobilize** [comment]
I'll close this for now, thanks for the help. Upgrading it definitely fixed a certain use case. I'll see if it happens again.
