### ISSUE TITLE
6.0.1 ready for new Mailjet response field "MessageUUID" by 2019-06-03?

### ISSUE THREAD

**Issue by moseb** [anymail/django-anymail#149]
Hi!

The Mailjet API will return responses containing a new field `MessageUUID` by 2019-06-03 as [announced here](http://go.mailjet.com/nl2/mtrq/mu8s3.html?m=AMQAADvXGGkAAce8F3oAAGcXGWQAAAAAAAEAIZ_ZAAKwkgBc2SdWswwutFWCSFGzJwnZqe0ofgACkQI). Is django-anymail 6.0.1 considered ready for that change?

Thanks in advance!

**Comment by medmunds** [comment]
All versions of Anymail that support Mailjet should be compatible with this change. (In general, Anymail simply ignores extra fields present in an ESP's API response.)

Anymail will still use Mailjet's legacy `MessageID` as Anymail's [`message_id`](https://anymail.readthedocs.io/en/stable/sending/anymail_additions/#anymail.message.AnymailStatus.message_id). If you need to access Mailjet's new `MessageUUID` field after sending a message, use Anymail's (non-portable) [esp_response](https://anymail.readthedocs.io/en/stable/sending/anymail_additions/#anymail.message.AnymailStatus.esp_response) status attribute to get the raw Mailjet response.

**Comment by moseb** [comment]
Thanks!
