### ISSUE TITLE
Sendinblue: Upcoming breaking changes in template sends

### ISSUE THREAD

**Issue by medmunds** [anymail/django-anymail#161]
[Edit] tl;dr: The next release of Anymail will only support Sendinblue's ["new" template language][new-template-language], and will lose the ability to send attachments with templates. Sendinblue users will need to [upgrade their templates](https://help.sendinblue.com/hc/en-us/articles/360000991960-How-to-convert-your-templates-to-the-New-Template-Language) for use with Anymail v7.0.

<hr>

ESP: Sendinblue
Anymail version: not-yet-released version including Sendinblue changes from #158

The next release of Anymail is likely to contain breaking changes for Sendinblue users who use Sendinblue templates: attachments will no longer be supported with templates, and you *may* need to convert each of your templates to Sendinblue's "new template language" using the upgrade link in their editor.

Please read on for details; comments and alternative proposals welcome.

## Background

Sendinblue has quietly released their ["new" Django-like template language][new-template-language], and has also quietly deprecated the v3 API that was used to send templates written in the "old" template language. The new API removes several limitations of the old one, but only when used with new-style templates. The new API also (in practice) *removes* the ability to send attachments with any templates.

Anymail v6.1 and earlier use the deprecated API for template sends. In #158 @Thorbenl has been kind enough to update Anymail's Sendinblue backend to use the new API for template sends. But this will introduce problems for older templates or for anyone wanting to send attachments with template email.

## Problem

If you have existing "old template language" Sendinblue templates, the changes introduced in #158 don't work as expected, and in some cases lose functionality compared to Anymail v6.1:

1. Display names in `to`, `cc`, and `bcc` emails do not appear\* in the sent message headers (works in 6.1)
2. `reply_to` overrides don't work\*; the sent message uses the template value (works in 6.1)
3. `from_email` and `subject` overrides don't work\*; the sent message uses the template values for both (new feature from #158, not available in 6.1)
4. Attachments don't work\*\* with templates (works in 6.1)

\* Limitations 1-3 only apply if your Sendinblue template is written in the "old" template language *and* the template contains `%PARAM%` personalization fields (Anymail `merge_data`). If your old-style template does not have any `%` params, *or* if you upgrade the template to Sendinblue's ["new" Django-style language][new-template-language], display names and header field overrides all work as expected.

\*\* Limitation 4, about attachments not working with templates, appears to be a deliberate design decision by Sendinblue, and is noted in their [v3/smtp/email](https://developers.sendinblue.com/reference#sendtransacemail) documentation. (They do have a way to pass attachment content by URL, but there's not really a way to map standard Django/Python attachment objects into that.)

[new-template-language]: https://help.sendinblue.com/hc/en-us/articles/360000268730-Using-the-SendinBlue-template-language-to-create-email-templates-NEW-

## Proposed resolution

I'm opening a support ticket with Sendinblue about limitations 1-3. I'm hoping it's just a bug and they'll be able to fix it. If not, users will need to upgrade their Sendinblue templates to the new language if they rely on any of these features. (There's a one-click upgrade in the Sendinblue template editor.)

Limitation 4 will be documented as an Anymail breaking change in the next release.

**Comment by medmunds** [comment]
More info on upgrading templates: https://help.sendinblue.com/hc/en-us/articles/360000991960-How-to-convert-your-templates-to-the-New-Template-Language

**Comment by medmunds** [comment]
The more I look into it, a simpler way to look at this is:
* Sendinblue has introduced an improved, Django-like "new" template syntax
* The new templates are not compatible with the old template send API
* Sendinblue sort of tried to make the new send API work with either old or new templates, but there's a bunch of stuff broken trying to use the *new* API with *old* templates

From Anymail's standpoint:
* There are a lot of advantages to Sendinblue's new templates, but it's not possible to use them from Anymail v6.1 (even with `esp_extra`)
* There's only one downside to new templates: they don't support (standard) attachments
* There's no easy way Anymail could determine which type of template you're using (like we do with some other ESPs), so it can't automatically choose the correct old/new API for you

The result is the next release of Anymail, v7.0, will *only* support Sendinblue's *new* templates. Sendinblue users will either need to upgrade their templates or stay with Anymail v6.x.

If any Anymail Sendinblue users have concerns about this plan, please raise them here.

**Comment by Thorbenl** [comment]
@medmunds Thanks for the active work on this :) We really appreciate it

**Comment by medmunds** [comment]
Changes as described were released in Anymail v7.0.

@Thorbenl thanks for the contribution! I wouldn't have even noticed SendinBlue added those features.
