### ISSUE TITLE
[Question]: How to handle ReadTimeout

### ISSUE THREAD

**Issue by SHxKM** [anymail/django-anymail#164]
Hi,

I think this is more question than error or bug. I've recently switched from SMTP based sending to API based sending in order to be able to tag my Mailgun transactional emails.
 I'm wondering about the error below and what's the best way to handle it. I _never_ saw these kind of errors before.

* Anymail version - 6.1.0

* ESP (Mailgun, SendGrid, etc.) - Mailgun

* Versions of Django, requests, python:

- Django: 2.1.11
- Python: 3.6.8
- requests: 2.20.0

* Exact error message and/or stack trace:

```
AnymailRequestsAPIError
Error posting to https://api.mailgun.net/v3/mg.myapp.io/messages:
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.mailgun.net', port=443): Read timed out. (read timeout=30)
Sending a message to myuser@emailaddress.com from MyApp <notifications@mg.myapp.io>
```

I'm wondering if I should be contacting Mailgun about this, or write logic that will retry the email sending task myself?

**Comment by medmunds** [comment]
Anymail is trying to post an HTTP request to Mailgun's API, and that request is timing out.

If this happens on *every* attempt to send, then `https://api.mailgun.net` is probably not reachable from the machine where you're running your Django app. Maybe you have a firewall that blocks outbound traffic (on port 443)?

If this happens on *most but not all* attempts (some sends work), it could be a temporary Mailgun issue (check their [status page](https://status.mailgun.com/)), or it could be a problem with your network configuration.

If this happens *intermittently*, that's not unusual behavior. Sometimes an ESP has a temporary outage, or sometimes your hosting provider has temporary networking issues, or sometimes things just go wrong. The Anymail docs have more info on [handling transient errors](https://anymail.readthedocs.io/en/stable/tips/transient_errors/). (The same issue applies to communicating with an SMTP API.)

**Comment by SHxKM** [comment]
@medmunds - Thanks for your detailed explanation.

When catching, do I `except AnymailRequestsAPIError` or `except requests.exceptions.ReadTimeout`?

**Comment by medmunds** [comment]
I'd probably catch [`AnymailAPIError`](https://anymail.readthedocs.io/en/stable/sending/exceptions/#anymail.exceptions.AnymailAPIError). It's a little more portable than the Requests specific version, in case you ever switch ESPs.

**Comment by SHxKM** [comment]
@medmunds - Thanks!
