### ISSUE TITLE
Add attachments to list of receivers

### ISSUE THREAD

**Issue by mcroni** [anymail/django-anymail#167]
Hi, this isnt exactly an issue but i am looking for a way to add different attachments to a mail i send out to multiple receivers and i am using mailgun as my backend email provider. Wondering if that can be done like the way `merge_data` works for individual recipients. Thanks

**Comment by medmunds** [comment]
I'm not sure if any of the ESP APIs support varying attachments in a batch send. There *might* be a way to hack it with Mailgun's `recipient_variables` API field, but it would probably be ugly.

Maybe consider just looping over your recipients and sending a separate message with attachments for each one. This is definitely portable to all ESPs, and is often easier to code for errors than a batch send (e.g., if something goes wrong with one recipient in a batch, it's not always clear whether messages were sent to the other recipients or not).

**Comment by mcroni** [comment]
sure, was also considering that case. Thanks for the help
