### ISSUE TITLE
Postmark batch support docs update

### ISSUE THREAD

**Issue by Honza-m** [anymail/django-anymail#168]
Hi,

Going through the documentation I've noticed that the table [this main ESP page](https://anymail.readthedocs.io/en/stable/esps/) shows that the Postmark implementation does not support the merge_data argument, however on the [ESP doc page](https://anymail.readthedocs.io/en/stable/esps/postmark/) the documentation says:

>Changed in version 4.2: Added Postmark merge_data and batch sending support. (Earlier Anymail releases only supported merge_global_data with Postmark.)

Could you please update the table to reflect that? It had me really sad and confused for a while.

Keep up the good work, anymail is awesome!

**Comment by medmunds** [comment]
Good catch, thanks.
