### ISSUE TITLE
Use alternative JSONEncoder for serializing merge data

### ISSUE THREAD

**Issue by tcourtqtm** [anymail/django-anymail#184]
As noted in [the docs](https://anymail.readthedocs.io/en/stable/sending/templates/#formatting-merge-data), anymail currently does not support certain data types when serializing merge data. In some cases, fixing the data to accommodate this restriction can be cumbersome.

For example, if you already have a serializer that produces the data needed, but which also includes properties with Decimals, dates, etc., then passing that to anymail requires manually fixing up the individual fields. For large, or deeply nested, data this might not be very desirable.

Could anymail have an option to use a different JSONEncoder? Being able to swap in a different encoder, like the [Django JSON encoder](https://docs.djangoproject.com/en/3.0/topics/serialization/#djangojsonencoder) or any other custom  one, would be a nice way to solve this.

**Comment by medmunds** [comment]
Thanks for the suggestion. There are a couple of ESPs whose APIs don't use JSON, so relying on a new Anymail option to format your merge data properly could make it difficult to change to another ESP later. 

One solution is to pass the data through your custom JSON encoder and back through the standard decoder before handing it off to Anymail:

```python
message.merge_data = json.loads(json.dumps(my_complex_data, cls=DjangoJSONEncoder))
```

That's a little ugly, but avoids manually fixing up individual fields, and is portable to ESPs that don't use JSON. (But beware that several ESPs only support a single level of merge data, so anything nested could still be setting you up for trouble later.)

That said, I'd be OK with switching Anymail to just use the DjangoJSONEncoder always. (And maybe making it easier to customize JSON encoding by subclassing an Anymail backend. Say, by changing the [`BasePayload.serialize_json`](https://github.com/anymail/django-anymail/blob/v7.1/anymail/backends/base.py#L529-L549) helper to grab an encoder `cls` from the payload's backend.)

**Comment by tcourtqtm** [comment]
Thanks for the quick reply! I didn't realize that the JSON formatting wasn't a universal path for every ESP. Using the Django encoder by default might be ok just to have basic support for these data types. However it does make some pretty specific choices about formatting so I wouldn't expect that to be a complete solution.

Being able to subclass a backend to provide a custom encoder would be pretty good.

**Comment by medmunds** [comment]
I started down the path of allowing backend subclasses to easily override the JSON encoder, but it's non-trivial. The catch is that some of the backends use CaseInsensitiveDict in their payload construction, and expect Anymail's JSON serialization to handle that for them. (The DjangoJSONEncoder doesn't.) So anyone wanting to substitute a custom JSON encoder would need to have it inherit from a new AnymailJSONEncoder or something similar. And at that point, I think the feature is becoming so complex that people are unlikely to use it.

Unless you have some other ideas, I'm probably going to close this as "won't fix". The simplest workaround is, where you construct your message:

```python
message.merge_data = json.loads(json.dumps(my_complex_data, cls=DjangoJSONEncoder))
```

If you really want to override the encoder through subclassing, that's possible in the current code, but you'll need to subclass both the backend and its payload:

```python
# Postmark example, but you could substitute any backend that uses a JSON-based API
from anymail.backends.postmark import EmailBackend, PostmarkPayload
from django.core.serializers.json import DjangoJSONEncoder

# use EMAIL_BACKEND = 'path.to.this.CustomBackend' in your settings.py
class CustomBackend(EmailBackend):
    def build_message_payload(self, message, defaults):
        # Use our CustomPayload to get custom JSON serialization
        return CustomPayload(message, defaults, self)

class CustomPayload(PostmarkPayload):
    def serialize_json(self, data):
        # make sure your CustomJSONEncoder can handle CaseInsensitiveDict
        return json.dumps(data, cls=CustomJSONEncoder)

class CustomJSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, CaseInsensitiveDict):
            return dict(o)
        else:
            return super().default(o)
```
