### ISSUE TITLE
pip install django-anymail[mailgun] - no matches found

### ISSUE THREAD

**Issue by banagale** [anymail/django-anymail#188]
It [looks like](https://github.com/anymail/django-anymail/blob/master/setup.py) only boto3 and sparkpost have requirements that can be added using the pypi extras option, is that correct?

Reason I ask is doing the default install given in readme, `pip install django-anymail[mailgun]` results in an error, in my case: `zsh: no matches found: django-anymail[mailgun]`

I am using mailgun and I realize it has no dependencies, which it says in the onboarding instructions. However, if that is not a valid example, perhaps it would be better to simply list the services that do have dependencies and provide a working command for the default install.

Edit: I see now [the docs](https://anymail.readthedocs.io/en/stable/installation/) do this but the readme perhaps is out of date? 
--
* Anymail version 7.1
* ESP (Mailgun, SendGrid, etc.) mailgun
* Your ANYMAIL settings (change secrets to "redacted")
* Versions of Django, requests, python
* Exact error message and/or stack trace
* Any other relevant code and settings (e.g., for problems
  sending, your code that sends the message)

**Comment by medmunds** [comment]
The examples in the docs all did work at the time the docs were written. So we need to identify what is different about your environment.

That error message seems to be coming from zsh, not pip. I'm not familiar with zsh (I run bash), but I'm guessing it may have different rules for what needs to be quoted to avoid globbing/filename expansion.

Please try (with single quotes around the package):

```zsh
pip install 'django-anymail[mailgun]'
```

If that fixes it, we should probably update the docs to quote the install package names, to help people running other shells.

Or if I've misunderstood and this really is a pip error, it would be helpful to know what versions of pip and python you are running. (`pip --version` and `python --version`.)

BTW, you're correct that currently only `[sparkpost]` and `[amazon_ses]` bring in extra dependencies. The docs suggest always including the ESP in the package name, though, to accommodate any future dependency changes.

**Comment by banagale** [comment]
@medmunds You were right it was a zsh issue. I added the single-quotes and it ran the dependency as expected. 

Thanks for that feedback.  Ya, if the quotes work more universally, it might save a few minutes for zsh users in the future.

**Comment by medmunds** [comment]
Oh, good. I'm going to treat this as a docs improvement issue: all the `pip install package[option]` commands should get single quotes around `'package[option]'`.

(Single quotes should work fine with all the shells I'm familiar with, but need to verify this won't cause problems for Windows users first.)
