### ISSUE TITLE
Minor feature request - Post-send signal to have esp_extra field

### ISSUE THREAD

**Issue by zehawki** [anymail/django-anymail#195]
Would it be possible to send the esp_extra param through to post_send signal?

Here's my usecase:

1. Standard mails go via SES, tracked via SES Event Publishing. This is the default config done by setting AMAZON_SES_CONFIGURATION_SET_NAME
2. At post_send, the info is written to the DB for tracking. All OK so far
3. Admin mails also go via SES, but these need not be tracked. So I've overridden this using msg.esp_extra (custom ConfigurationSetName) when sending these mails out. This is also working as expected.
4. But now at post_send, I dont find the esp_extra field, so cant prevent this needless write to DB.

I've looked through the documentation and I think its not provided...

OR is there another way to handle this usecase?

**Comment by medmunds** [comment]
The `message` arg to your post_send signal handler is the actual EmailMessage object that was sent. That should have an esp_extra property if there was one when you sent it. Is that not working?

**Comment by zehawki** [comment]
Ahhhhhh, its a **property**. I was doing

`if 'esp_extra' in message:`

which was not working. Now changed to

`if not hasattr(message, 'esp_extra'):`
