### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by simondrabble** [anymail/django-anymail#201]
Is there a way to have ESP credentials etc pulled from a database table instead of directly in settings? In a multi-tenant architecture, having a single app instance serve multiple tenants, it is useful to separate out mailing configs (and potentially even ESPs). At least having the ability to use an API key, domain etc driven from the database would go a long way towards supporting this use case.

**Comment by medmunds** [comment]
You could use Django's `django.core.mail.get_connection()` function to instantiate an EmailBackend for a particular tenant at the point you need it. See the examples in the [*Mixing email backends*](https://anymail.readthedocs.io/en/stable/tips/multiple_backends/) section of Anymail's docs. All of Anymail's backends support supplying API keys or other credentials via `get_connection()` kwargs, and all of Django's email sending functions support using a specific `connection` in place of the default one from settings.

There's no realistic way this could be built into Anymail. The "active tenant" usually depends on some sort of HttpRequest data like the hostname or an HTTP header. Django's EmailBackend mechanism—which is what Anymail plugs into—is completely independent of request processing, so doesn't have access to the "current request." Plus email can be sent from contexts (like management commands) that don't even involve a request.

**Comment by simondrabble** [comment]
That's exactly what I was looking for - thanks!

**Comment by simondrabble** [comment]
Following up.. it looks like I can pass credentials into get_connection, but each ESP has different credentialing parameters.. is there any documentation for each, or is it a case of digging into the code?

**Comment by medmunds** [comment]
Heh, it's more a case of digging through the docs. There's a page for [each supported ESP](https://anymail.readthedocs.io/en/stable/esps/) that documents its settings variables. And then the main [settings docs](https://anymail.readthedocs.io/en/stable/installation/#anymail-settings-reference) mention converting settings variable names to get_connection params: "To get the kwargs parameter for a setting, drop “ANYMAIL” and the ESP name, and lowercase the rest."

**Comment by simondrabble** [comment]
Great! I missed that second part in the docs, thanks for the info!
