### ISSUE TITLE
AnymailRequestsAPIError

### ISSUE THREAD

**Issue by mikeromanov** [anymail/django-anymail#218]
I'm developing an educational project using Django + cookiecutter-django.

This cookiecutter has default mail backend Maingun Anymail (`EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"`).

I've registered on Mailgun.com a subdomain mail.raptors.ru of my own domain (raptors.ru). It passed verification and got api key and other settings (see below). However, it does not seem to work. When I try to register a new user, django users app tries to send a verification email and fails. Instead, I receive error message.

```
AnymailRequestsAPIError at /accounts/signup/

Invalid JSON in Mailgun API response
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Sending a message to michael_romanov@inbox.ru from postmaster@mail.raptors.ru
Mailgun API response 200 (OK): 'Mailgun Magnificent API'
```
I'm stuck with it. Please help me anyone. My settings are following:

settings/production.py:
```
INSTALLED_APPS += ["anymail"]  # noqa: F405
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
# https://anymail.readthedocs.io/en/stable/installation/#anymail-settings-reference

ANYMAIL = {
    "MAILGUN_API_KEY": env("MAILGUN_API_KEY"),
    "DEBUG_API_REQUESTS": True,  # don't leave this enabled in production
    "MAILGUN_SENDER_DOMAIN": env("MAILGUN_DOMAIN"),
    "MAILGUN_API_URL": env(
        "MAILGUN_API_URL", default="https://api.mailgun.net/v3"
    ),
}
```
.env:
```
MAILGUN_API_KEY=*******
MAILGUN_DOMAIN=mail.raptors.ru
MAILGUN_API_URL=https://api.eu.mailgun.net/v3/mail.raptors.ru/messages
```
Package version is:
`django-anymail[mailgun]==7.2.1`

![изображение](https://user-images.githubusercontent.com/33122675/104309599-76a89080-54e3-11eb-97f4-72f72a72b207.png)

**Comment by medmunds** [comment]
Thanks for including all of your settings, that makes it much easier to understand the issue.

The problem is that the MAILGUN_API_URL setting must be only the base url for the Mailgun API—don't include your MAILGUN_DOMAIN in it (see [MAILGUN_API_URL docs](https://anymail.readthedocs.io/en/stable/esps/mailgun/#std-setting-ANYMAIL_MAILGUN_API_URL)). You should be able to fix it by changing your .env from:

```env
MAILGUN_API_URL=https://api.eu.mailgun.net/v3/mail.raptors.ru/messages
```

to:

```env
MAILGUN_API_URL=https://api.eu.mailgun.net/v3
```

**Comment by mikeromanov** [comment]
Thank you so much, Mike!

Your recipe works!!! I'm completely happy! (This has been driving me crazy last two days)

Good luck to you and best wishes in the new year!

Mike
