### ISSUE TITLE
merge_data converts embedded list to string

### ISSUE THREAD

**Issue by asterstarts** [anymail/django-anymail#222]
JSON encoder for anymail converts merge_data embedded list into a string. When I set merge_data to:
```
	"user-variables": {
		"name": "Nasdf",
		"invoice_details": [{'amount': 0, 'description': 'Entry'}],
		"purchase_date": "Feb 03 2021 06:33:16",
		"invoice_id": "0DF2440D-0005",
		"date": "Feb 03 2021 06:33:16",
		"total": "$0.00",
		"plan_name": "Entry"
	}
```

This gets sent as:
```
	"user-variables": {
		"name": "Nasdf",
		"invoice_details": "[{u'amount': 0, u'description': u'Entry'}]",
		"purchase_date": "Feb 03 2021 06:33:16",
		"invoice_id": "0DF2440D-0005",
		"date": "Feb 03 2021 06:33:16",
		"total": "$0.00",
		"plan_name": "Entry"
	},
```

`invoice_details` is coerced to a string. This happens no matter how `invoice_details` is treated. Are nested structures not allowed?

Reporting an error? It's helpful to know:

* Anymail version - 7.1.0
* ESP (Mailgun, SendGrid, etc.) - Mailgun
* Versions of Django, requests, python - Django 3.0.5, python 3

**Comment by medmunds** [comment]
It sounds like you are running into a [known limitation of Mailgun's API](https://anymail.readthedocs.io/en/stable/esps/mailgun/#limitations-with-stored-handlebars-templates):

> Mailgun’s API does not allow complex data types like lists or dicts to be passed as template substitutions for a batch send (confirmed with Mailgun support 8/2019). Your Anymail merge_data and merge_global_data should only use simple types like string or number.

That same doc link includes a (non-portable) workaround if you are only sending to a single recipient at a time.

If that's not the problem you're seeing, it would help to understand what you're trying to do and see the code you're using to send the message.

**Comment by asterstarts** [comment]
This is the issue, thanks for checking
