### ISSUE TITLE
"pip install django-anymail --upgrade" upgrades django

### ISSUE THREAD

**Issue by ojwoodford** [anymail/django-anymail#23]
I had Django=1.8.3 already installed, which I believe is already supported by django-anymail. But when I ran:

`pip install django-anymail --upgrade`

just now, pip also upgraded my django to the latest version. I want to stick with Django 1.8, and don't believe this should have been upgraded automatically.

I'm not sure if this is a problem with django-anymail settings or pip.

**Comment by ojwoodford** [comment]
Actually it also upgraded requests from 2.7.0 to 2.10.0

**Comment by ojwoodford** [comment]
Actually, I think this is standard (annoying) pip behaviour.

**Comment by medmunds** [comment]
Yep, this is all normal pip behavior, not specific to anymail.

`pip --upgrade <package>` by default upgrades all of *package*'s dependencies. Add the [`--no-deps`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption--no-deps) option to restrict the upgrade to *package*.
