### ISSUE TITLE
Mailgun Webhook receiver began erroring in the last 24 hours

### ISSUE THREAD

**Issue by wadewilliams** [anymail/django-anymail#233]
* Anymail 8.2
* Mailgun
* Django 3.1.7, requests 2.25.1, python 3.8.8

Sentry has begun reporting the following error in the last 24 hours. It still appears that most events are getting processed properly. I'm guessing this is on Mailgun's side but I figured it was prudent to post here as well.

It would appear that the mailgun webhook is calling our receiver with no JSON.

```
Mailgun webhook called with invalid payload format json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

<img width="632" alt="Screen Shot 2021-03-26 at 1 13 04 PM" src="https://user-images.githubusercontent.com/1676891/112681954-013b3380-8e35-11eb-91c9-8226481f6a43.png">

**Comment by medmunds** [comment]
Weird. 

An empty request body would cause this error. So would invalid JSON starting with something other than `{`, `[` or `"`. For example, if something in between Mailgun and your Django app was replacing the JSON post body with a plain text error message, you'd get this same error. (Looks like your app is behind Heroku's Vegur proxy—could that be modifying the incoming request?)

I believe Mailgun's dashboard logs exactly match the tracking events they send through webhooks. You might be able to find the events in their logs that match the webhook events Anymail couldn't parse, and see if there's anything unusual about them.

**Comment by wadewilliams** [comment]
I'm running it up with Mailgun now but it seems that the failing hooks are always from the user agent `Go-http-client/1.1` instead of `mailgun/treq-16.12.0`, and I noticed the logger is `django.security.AnymailWebhookValidationFailure`

- Any chance the user agent has anything to do with this as far as django-anymail is concerned?

**Comment by wadewilliams** [comment]
I'll close this because Mailgun has said it's on their end.
