### ISSUE TITLE
Receiving 401 with Mailgun setup

### ISSUE THREAD

**Issue by k-flynn-webdev** [anymail/django-anymail#237]
Using latest version of Anymail I've setup my project all my details work with a node.js project just fine. But on my Django project I always receive a 401 forbidden error, i've tried multiple versions of MAIL_HOST [api.eu.mailgun.net, https://api.eu.mailgun.net/v3, https://api.eu.mailgun.net/v3/mail.kubedev.co.uk ] but no joy, any ideas?

**Error**
> anymail.exceptions.AnymailRequestsAPIError: Sending a message to xxxxxx@gmail.com from hi@kubedev.co.uk
> Mailgun API response 401 (UNAUTHORIZED): 'Forbidden'

**.env**
> MAIL_FROM="hi@kubedev.co.uk"
> MAIL_HOST="api.eu.mailgun.net"
> MAIL_DOMAIN="mail.kubedev.co.uk"
> MAIL_API="key-lotsOfThingsHerexxxxxxxxxxxxx"

**settings.py**
> ANYMAIL = {
>     # (exact settings here depend on your ESP...)
>     "MAILGUN_API_KEY": os.getenv("MAIL_API"),
>     "MAILGUN_API_URL": os.getenv("MAIL_HOST"),
>     "MAILGUN_SENDER_DOMAIN": os.getenv("MAIL_DOMAIN"),
> }
> SERVER_EMAIL = os.getenv("MAIL_FROM")  # ditto (default from-email for Django errors)
> DEFAULT_FROM_EMAIL = os.getenv("MAIL_FROM")  # if you don't already have this in settings
> EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"  # or sendgrid.EmailBackend, or...
> 
> INSTALLED_APPS = [
> ....
>     # MAIL
>     'anymail',
> ....
> ]

**Comment by k-flynn-webdev** [comment]
I was doing something silly, ignore this post.

**Comment by piotrsynowiec** [comment]
Hi, can you share with me how have you fixed this problem? I have the same one, and can't figure out what I am doing wrong.

**Comment by 0x78f1935** [comment]
> For other users – if you have this problem, check if you have the correct MAILGUN_API_URL for EU domains: https://anymail.dev/en/stable/esps/mailgun/

Legend
