### ISSUE TITLE
Emails using SparkPost templates arrive empty

### ISSUE THREAD

**Issue by ojwoodford** [anymail/django-anymail#24]
I use two approaches for sending email:

1. Use django.core.mail.send_mail() and send the email template along with the parameters.
2. Use django.core.mail.EmailMessage() and django.core.mail.get_connection().send_messages() to use an email template in my ESP account.

I have been using Mandrill up until now, and want to switch to SparkPost. I have configured and published templates in both my Mandrill and SparkPost accounts, and my API keys for both services. The slug for a given template on Mandrill is the same as both the name and ID of the equivalent template on SparkPost. I used SparkPost's migration tool so this should be correct.

When I switch the email backend from anymail.backends.mandrill.MandrillBackend to anymail.backends.sparkpost.SparkPostBackend, the emails sent via send_mail() come through fine, but the emails using the templates, sent via send_messages(), arrive with an empty message body, i.e. there is no email. I can send the templates as test emails with dummy data via the SparkPost dashboard just fine.

**Comment by medmunds** [comment]
Just to double-check: you've switched your code to use `template_id` rather than `template_name` (and `merge_data` rather than `merge_vars`), right?

(If you're migrating from Djrill, some of the Mandrill-specific attributes [have been renamed](http://anymail.readthedocs.io/en/latest/esps/mandrill/#changes-to-emailmessage-attributes) in Anymail. The old Djrill attrs are still supported -- with deprecation warnings -- in Anymail's Mandrill backend, but not in the other ESP backends. Full list and a grep to help find them in the doc link above.)

If that's not the problem, it would be helpful to see the specific code that isn't working.

**Comment by ojwoodford** [comment]
I didn't see any warnings in my console, but I'm setting the:

- `template_name`
- `global_merge_vars`

attributes of my EmailMessage object before sending. I'm using Django 1.8.

It's difficult to know what code isn't working, because there are no errors.

If I change `template_name` to `template_id` I do get an error:
```
Exception Type:	AnymailAPIError
Exception Value:	
Call to https://api.sparkpost.com/api/v1/transmissions returned 422, errors:
        invalid combination of fields: Both content object and template_id are specified
        
Sending a message to xxx from xxx
ESP API response 422:
{
  "errors": [
    {
      "message": "invalid combination of fields", 
      "code": "1301", 
      "description": "Both content object and template_id are specified"
    }
  ]
}
```

**Comment by medmunds** [comment]
OK, there are two problems here:

1. Anymail has a bug with SparkPost stored templates leading to the 422 response you've listed above. I'm looking into that right now.

2. Your code is using the old Djrill attribute names. You'll need to update them before switching from Mandrill to another Anymail ESP backend (like SparkPost). Please read through Anymail's docs on [migrating from Djrill](http://anymail.readthedocs.io/en/latest/esps/mandrill/#migrating-from-djrill) and change your code as needed.

To assist with migrating from Djrill to Anymail, Anymail issues DeprecationWarnings *when you are using Anymail's Mandrill backend* and use the Djrill names. (The new Anymail backends like SparkPost don't even bother looking for the old Djrill names. It's best to work through the migration docs before switching ESPs.)

Those warnings should show up in your dev server logs (and Django test output, if you have tests on email sending). If you'd like to change the warnings to errors to make them more visible see [this StackOverflow answer](http://stackoverflow.com/a/16457346/647002).

Or you can run this `git grep` command at the root of your project to find all instances of old Djrill names that need updating (from [the migration docs](http://anymail.readthedocs.io/en/latest/esps/mandrill/#changes-to-emailmessage-attributes)):

```shell
git grep -w \
  -e 'async' -e 'auto_html' -e 'auto_text' -e 'from_name' -e 'global_merge_vars' \
  -e 'google_analytics_campaign' -e 'google_analytics_domains' -e 'important' \
  -e 'inline_css' -e 'ip_pool' -e 'merge_language' -e 'merge_vars' \
  -e 'preserve_recipients' -e 'recipient_metadata' -e 'return_path_domain' \
  -e 'signing_domain' -e 'subaccount' -e 'template_content' -e 'template_name' \
  -e 'tracking_domain' -e 'url_strip_qs' -e 'use_template_from' -e 'use_template_subject' \
  -e 'view_content_link'
```

**Comment by ojwoodford** [comment]
[This stackoverflow question](http://stackoverflow.com/questions/36651369/how-to-send-a-stored-template-and-also-specify-reply-to-from-name-and-from-emai/36868847#36868847) is also relevant. That's where I (and possibly anymail) am going wrong.

**Comment by medmunds** [comment]
Ah - thanks -- that's exactly the problem. I'll have to figure out how to convince python-sparkpost not to put anything else in the content payload.

**Comment by medmunds** [comment]
Pushing a fix momentarily. Until then, workaround is to explicitly specify `subject=None, body=None` on your EmailMessage. (SparkPost is balking on the default empty strings for these fields.)

**Comment by ojwoodford** [comment]
Many thanks @medmunds. The workaround has done the trick. Any chance of a new version number so that I can pip install on a server? No worries if not.

**Comment by medmunds** [comment]
No problem -- thanks for catching it and identifying the cause.

New version will be 0.4.2. Just waiting for Travis-CI to approve, and then will push to PyPI.

**Comment by medmunds** [comment]
[Release 0.4.2](https://pypi.python.org/pypi/django-anymail) is live
