### ISSUE TITLE
Inconsistency in testing environment when sending mass emails.

### ISSUE THREAD

**Issue by Genetical** [anymail/django-anymail#249]
**Python Version:** `3.9.7`
**Django Version:** `3.2.7`
**Requests Version:** `2.26.0`
**Anymail Version:** `8.4`
**ESP:** `Postmark`

When sending an email job to an ESP, you can set the `merge_data` param to be an empty dictionary. This will result in individual emails sent to each recipient in the `to` param. 

If 10 emails are given, each recipient will recieve the email but will only see their own email in the recipient field as opposed to a list of all the recipients. The below code functions as expected when sent to an ESP. 

```python
if merge_data is None:
    merge_data = {}

log.info(f"Email job triggered. Sending to {len(recipients)} emails. Subject line: {subject}")

message = EmailMessage(
    subject=subject, body=body, from_email=sender, to=recipients, reply_to=reply_to
)

message.content_subtype = "html"
message.template_id = template_id
message.merge_data = merge_data
message.merge_global_data = merge_global_data
message.esp_extra = esp_extra

try:
    log.info(f"Sending email request to ESP. Attempt {self.request.retries + 1} of 5.")
    message.send()
except AnymailAPIError as exc:
    log.warning(f"API Error when communicating with ESP: {exc}")
    self.retry(exc=exc, countdown=int(random.uniform(2, 4) ** self.request.retries))
    # Countdown set to an exponential backoff with random jitter.
```

However, when running this code in a test environment (i.e Setting the email backend to `anymail.backends.test.EmailBackend`), only one `EmailMessage` object will be added to `mail.outbox` with all of the recipients in the one email's `to` attr.

Would it be possible for the test email backend to identify when `merge_data` has been defined and to instead generate an individual email for each recipient in the outbox to better replicate how ESP interactions work? Thank you

**Comment by Genetical** [comment]
Thank you for this response. What you said about each message representing an API call makes complete sense, so I understand you not wanting to change it. You could possibly consider creating a separate test backend to better emulate an esp which subclasses the main test backend (in the fashion you demonstrated above) for when people do want to more closely mock an ESP.

Regarding the copy method, I've glanced over the EmailMessage definition and the only alternative I can see is just to construct the messages "manually" in the `post_to_esp` method. Although I'm not sure if that would result in the same value for attributes like the date and id.

I wonder if it may be a better idea to make batch emails a more distinct action in general and use a custom function (e.g "send_batch_email") than just setting merge_data to an empty dict. Then in the test backend, represent the batch email with something like a `BatchEmail` class which returned an iterable of `EmailMessage`'s.

**Comment by medmunds** [comment]
> I wonder if it may be a better idea to make batch emails a more distinct action in general and use a custom function (e.g "send_batch_email") than just setting merge_data to an empty dict.

Simple answer: yes. (But things are rarely simple.)

Django's EmailMessage isn't a great abstraction for modeling batch sends, and I've never been particularly happy with using `merge_data` and `merge_metadata` as the markers for batching. Anymail inherited this from the predecessor Djrill project, which itself was just reflecting how MailChimp's Mandrill API identified batch sends. 

If we were designing from scratch, I'm sure there'd be a better way to handle this. (It would also be nice to support the more-flexible batching offered by some ESPs, where subjects, message bodies, attachments, and other data can be specified separately for each recipient in the batch.)

Redesigning Anymail's batch send API is a broader topic than just the test EmailBackend. (Anymail needs to fit within Django's email APIs, and to play nicely with other Django add-ons that augment email. We'd have to figure out a smooth migration path for any API changes. Etc.) If you're interested in pursuing this, could I ask you to open a topic in the discussions? It would be helpful to clarify the goal, explore a proposal, and to give others using batch send a chance to weigh in.

As far as the test EmailBackend, I've exposed a new `is_batch_send` param and added this to the docs to try to clarify the behavior:

> Note that `django.core.mail.outbox` is an "outbox," not an attempt to represent end users' *inboxes*. When using Django's default locmem EmailBackend, each outbox item represents a single call to an SMTP server. With Anymail's test EmailBackend, each outbox item represents a single call to an ESP's send API. (Anymail does not try to simulate how an ESP might further process the message for that API call: Anymail can't render [ESP stored templates](#), and it keeps a [batch send](#) message as a single outbox item, representing the single ESP API call that will send multiple messages. You can check `outbox[n].anymail_test_params['is_batch_send']` to see if a message would fall under Anymail's batch send logic.)

I'd like to keep Anymail's test EmailBackend simple and focused on what Anymail needs to test its own code, and don't really want to start down the slippery slope of emulating an ESP. (Also, I don't think it would be appropriate to change the semantics of Django's test outbox.)

If you'd find it helpful to develop an alternative test backend that instead generates its own "inbox" or tries to simulate other ESP behavior, that could easily be released as a separate package (and I'd be happy to include it in the Anymail docs).
