### ISSUE TITLE
Consider including esp_extra to EmailMultiAlternatives example in Anymail 1-2-3

### ISSUE THREAD

**Issue by banagale** [anymail/django-anymail#26]
The Anymail 1-2-3 document example is for Mailgun, but it does not directly address Mailgun's suggestion of using a subdomain to send mail:

"_We recommend using a subdomain with Mailgun, like “mg.mydomain.com”. Using a subdomain you will still be able to send emails from your root domain e.g. “you@mydomain.com”._"

Anymail does support this setting via [esp_extra](https://anymail.readthedocs.io/en/latest/esps/mailgun/), but the example using EmailMultiAlternatives does not demonstrate the use of this.

Since the recommendation from mailgun is to use a subdomain, I recommend adding a line, 

`msg.esp_extra = {"sender_domain": "example.com"}, # change to mg.example.com or other subdomain if necessary.` 

which demonstrates how to manually set this. This helps avoid a potential [beginner stumbling block](http://stackoverflow.com/questions/37375532/mailgun-domain-not-found-abc-com/38058296).

**Comment by medmunds** [comment]
Thanks for the suggestion -- and for helping the person on SO.

This seems like a common-enough case (per [Mailgun recommendations](https://help.mailgun.com/hc/en-us/articles/202256730)), that I think it's worth adding a setting specifically for this.

I'm going to add MAILGUN_SENDER_DOMAIN to the ANYMAIL settings, and I'll include that in the 1-2-3 example. (That would also provide a simpler solution for the SO question you linked, where you deduced they were using send_mail.)

Default without this setting will still be to extract sender_domain from the from_email. And sender_domain will still be supported in esp_extra for individual message overrides. (E.g., Mailgun's example of using different subdomains for transactional vs. marketing email.)

**Comment by banagale** [comment]
Sounds good. If you can bump this when this is part of a release, I'll update my SO answer.

**Comment by medmunds** [comment]
Released in v0.5

**Comment by banagale** [comment]
Updated. Thanks for your effort on this product.
