### ISSUE TITLE
Save all send mail with webhook status from backends

### ISSUE THREAD

**Issue by ebertti** [anymail/django-anymail#27]
Create a settings like:
```python
ANYMAIL_LOG_MAIL = True
```
And store all email data, like: subject, template_name, context, to, final_html, from, datetime, generic relation to mail object (ex: user, order, alert ...) . AND the last status sent by backend webhook, like bounce, received, open.

Can be a campaign related to this email. Will be helpful for stats like: How many emails are bounce, received, open.

**Comment by medmunds** [comment]
I really like the idea of having an ESP-tracking dashboard available. However, I don't think it belongs inside django-anymail itself. I think it could be a separate Django reusable app that would work together with Anymail if both are installed together.

Here's my thinking:

* I really want to avoid storing anything in Anymail. As soon as you introduce models, you also introduce a lot of maintenance complexity... migrations, how to do cleanup (so the log doesn't grow unbounded -- cron jobs? celery tasks?), etc. That's fine--and expected--for an ESP dashboard app, but I wouldn't want to impose it on people who just want django-anymail for sending or receiving through an ESP.

* Just logging the raw data is relatively easy. ([Anymail's signals](https://anymail.readthedocs.io/en/latest/sending/signals/#post-send-signal) were meant to support this, and there's an example in the docs.) But there's a lot more work in putting together a useful stats dashboard on top of that--and making it perform well with lots of data. That feels beyond the scope of django-anymail.

* All the ESPs that Anymail supports offer already offer some sort of dashboard, with varying degrees of support for the stats you mentioned. (Though all have some limitations. And you can't migrate the historical stats if you're switching ESPs.)

BTW, there was [something similar](https://github.com/brack3t/Djrill/issues/102) discussed over in the Djrill project last year.

If you (or anyone) is interested in starting an ESP-dashboard project like this, I'd be happy to contribute.
