### ISSUE TITLE
sendinblue is not working

### ISSUE THREAD

**Issue by bluebamus** [anymail/django-anymail#273]
Reporting an error? It's helpful to know:

* Anymail version : django-anymail-8.5
* ESP (Mailgun, SendGrid, etc.) : sendinblue
* Your ANYMAIL settings (change secrets to "redacted")

from decouple import config

pip install "django-anymail[sendinblue]"

EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
SENDGRID_API_KEY = config('SENDGRID_API_KEY')
DEFAULT_FROM_EMAIL = config('SENDGRID_DEFAULT_FROM_EMAIL')

INSTALLED_APPS = ['anymail',]

* Versions of Django, requests, python : Django==4.0.3
* Exact error message and/or stack trace : 
- it's not working, I have been clean install django with test also.

* Any other relevant code and settings (e.g., for problems
  sending, your code that sends the message)

from decouple import config

mailgun also doesn'y work....

pip install "django-anymail[mailgun]"

EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"

ANYMAIL = {
    "MAILGUN_API_KEY": config('MAILGUN_ACCESS_KEY'),
}

**Comment by medmunds** [comment]
Sorry, it's a little hard to figure out what problem you're trying to solve. Which ESP do you want to use? (You mention Sendinblue, SendGrid, and Mailgun, and seem to be mixing together settings for all three.)

What exactly is "not working"? What are you trying to do, and how are you trying to do it? What do you expect to happen, and what actually happens that seems wrong? Are there any error messages?

It would probably help to work through the troubleshooting suggestions at https://anymail.dev/en/stable/help/#troubleshooting

**Comment by medmunds** [comment]
@bluebamus Did you figure out the problem? Please provide more detail if you're still having an issue. (See my earlier comment.)
