### ISSUE TITLE
SendGrid: update to new v3 send API

### ISSUE THREAD

**Issue by medmunds** [anymail/django-anymail#28]
SendGrid has [released](https://sendgrid.com/blog/introducing-v3mailsend-sendgrids-new-mail-endpoint) a new [v3 send API](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html). Should update Anymail to switch to that.
- Maybe consider running on official [sendgrid-python](https://github.com/sendgrid/sendgrid-python) package? (It's receiving maintenance again.)
- Will cause breaking changes in esp_extra for SendGrid users. (But probably worth it, since v3 API params are generally cleaner -- no more x-smtpapi.)
- [Sandbox mode](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/sandbox_mode.html) may be useful for integration tests
- Still doesn't seem to support multiple Reply-To (in reply_to param)

**Comment by medmunds** [comment]
One potential problem is that the v3 API is only documented to support [API-key authentication](https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/authentication.html). At least some Anymail SendGrid users are still on username/password auth (see #9), which apparently only works with the v2 API.

**Comment by Benoss** [comment]
What about creating a new backend sendgrid_v3 and use the sendgrid official library.
This way users can migrate to v3 with anymail more easily.
If using login/password then use the old backend else use the v3 backend

**Comment by medmunds** [comment]
Yeah, I think that's the best approach. I'm hoping to avoid supporting two different SendGrid APIs indefinitely, but it'll help smooth the transition.

Since v3 is the future, I'm leaning toward renaming the current v2 backend to something like SendGridV2, and making just plain "SendGrid" use v3. (It can warn if it detects attempts to use v2-only features like username auth.) It's a breaking change for the next Anymail release, but deprecating v2 implies a breaking change sooner or later, and sooner is probably better.

Also, it looks like there's now documentation on [using SendGrid API keys on Heroku](https://devcenter.heroku.com/articles/sendgrid#setup-api-key-environment-variable). Since Heroku's integration was the source of the earlier username/password-auth request (#9), hopefully that's no longer an issue for those users.

**Comment by digitaldavenyc** [comment]
What's the timeline look like for this?

**Comment by medmunds** [comment]
@digitaldavenyc I'm hoping to get to SendGrid v3 shortly after the new year. (The fix for the ugettext_lazy issue in #34 might involve a deep change in the base backend, so I want to get that worked out before developing any new backends.)

**Comment by medmunds** [comment]
Quick status update: this code is complete and merged into master. I'm just waiting for clarification from SendGrid on an API issue before releasing it (and the rest of Anymail v0.8).

**Comment by Benoss** [comment]
Awesome work 👍

**Comment by medmunds** [comment]
... *still* waiting to hear back from SendGrid on that API issue. If I don't get a response soon, will probably need to back this out so I can release the remainder of Anymail v0.8.

**Comment by medmunds** [comment]
OK, SendGrid has sorted out the v3 API issue, and I've released Anymail v0.8 with this code. Thanks for your patience.
