### ISSUE TITLE
Can't use merge_metadata with Mailgun 

### ISSUE THREAD

**Issue by meesix** [anymail/django-anymail#282]
* Anymail version — 8.6
* ESP (Mailgun, SendGrid, etc.) — Mailgun
*  django 4.0.4, requests 2.27.1, python 3.10
* Settings:
```
ANYMAIL = {
    "MAILGUN_API_KEY": "",
    "MAILGUN_SENDER_DOMAIN": '',  
    "MAILGUN_API_URL": "https://api.eu.mailgun.net/v3",
    "WEBHOOK_SECRET" : "",
    "MAILGUN_WEBHOOK_SIGNING_KEY": "",
}
```

I'm trying to add some metadata to emails, but never receive it in logs and in webhooks.

Here is what I'm doing:

```
recipient_variables = {recipient:metadata}
msg.merge_metadata = recipient_variables
```

This is how the msg.merge_metadata looks like:
```{'EMAIL': { 'submission_id': 'ID'}}```

This is what data looks like in Mailgun web logs:
```
	"user-variables": {
		"submission_id": "%recipient.v:submission_id%",
	},
```

And webhook just receives:
```{'submission_id': ''}```

I also tried 
```
msg.extra_headers["X-Mailgun-Recipient-Variables"] = json.dumps(recipient_variables)
```

It also hasn't changed anything much, but webhook now receives this instead>
```{'submission_id': '%recipient.v:submission_id%'}```

Am I doing anything wrong? The whole process seems to be pretty straightforward.

**Comment by medmunds** [comment]
> And webhook just receives:
> `{'submission_id': ''}`

The most likely explanation for this is Anymail didn't find that recipient's email in your `merge_metadata`. (Look for "merge_metadata values default to empty string" in Anymail's [Mailgun quirks docs](https://anymail.dev/en/stable/esps/mailgun/#limitations-and-quirks).)

The "recipient" key in your `merge_metadata` must exactly match the *email address* portion of the recipient's email, and is case sensitive. Here's an example:

```python
msg = EmailMessage(..., to=["Someone <someone@example.com>", "OTHER@example.com"], ...)
msg.merge_metadata = {
    "someone@example.com": {"submission_id": "a1234"},
    "OTHER@example.com": {"submission_id": "b5678"},
}
```

If that doesn't help, please provide a more complete example of the code you're using to generate and send the message. You can safely use example.com addresses (like I've done above) as a substitute for real emails.

**Comment by meesix** [comment]
Thank you so much for your explanation! It gave me an idea. I used `Someone <someone@example.com>` in `to` field, and I used the same value for merge_metadata, while I had to strip it from the name and use email only. 

So this one *doesn't* work:
```
msg.merge_metadata = {
    "Someone <someone@example.com>": {"submission_id": "a1234"},
}
```

And this one *does* work:

```
msg.merge_metadata = {
    "someone@example.com": {"submission_id": "a1234"},
}
```
