### ISSUE TITLE
RemovedInDjango50Warning: `webhooks/sparkpost.py`

### ISSUE THREAD

**Issue by jensenbox** [anymail/django-anymail#290]
Not a high priority but would be nice to clean up the terminal output:

https://github.com/anymail/django-anymail/blob/7d726734eb09fa1e3f4d3ce37ac1a22a46436e22/anymail/webhooks/sparkpost.py#L5

```shell
anymail/webhooks/sparkpost.py:5: RemovedInDjango50Warning: The django.utils.timezone.utc alias is deprecated. Please update your code to use datetime.timezone.utc instead.
    from django.utils.timezone import utc
```

**Comment by medmunds** [comment]
This has already been fixed (but not yet released) in a4f50c434063f03e6c516f7fe8c84f095c7b5d8f.
