### ISSUE TITLE
Latest commit not available with pip install

### ISSUE THREAD

**Issue by cocobuster** [anymail/django-anymail#30]
Thanks for django-anymail but I notice that your latest release for 'Mailgun: Add MAILGUN_SENDER_DOMAIN setting' Is not available through 'pip install django-anymail[mailgun]'

It would be useful to have access to the 'MAILGUN_SENDER_DOMAIN' new feature.

thanks!

**Comment by medmunds** [comment]
Sorry about that. v0.5 is now live on PyPI.

**Comment by cocobuster** [comment]
Great! thank you ;)
