### ISSUE TITLE
Sendpulse ESP (www.Sendpulse.com) integration

### ISSUE THREAD

**Issue by infosrabah** [anymail/django-anymail#318]
Hi Anymail folks,

Is there any chance to see sendpulse ESP (https://sendpulse.com) integrated into django anymail pacakge ?

The reason being is : We really want to use Django anymail package, for the automation and switch from ESP to another in case of .... But the problem is that the Majority of ESP that come with Anymail has entry barrier... we just get suspended by 3 of them, even if we supply them with all information about (domain and pro email, and explain the business nature).... but with ESP like sendpulse it's kinda smooth...

Thank you.

**Comment by infosrabah** [comment]
Sendpulse just changed to brevo.com

I'll open another issue accordingly

**Comment by infosrabah** [comment]
Issue

**Comment by medmunds** [comment]
SendPulse appears to be primarily a bulk email service. Their transactional email offering (which they call "SMTP Service") could be made to work with Anymail, but their [HTTP transactional API](https://sendpulse.com/integrations/api/smtp#send-email-smtp) seems relatively limited. (E.g., there's not even a way to supply a Reply-To address. And they don't have any of the extended ESP features like metadata or tags, which are where Anymail starts adding value over Django's built-in email support.) 

Given their limitations, I'm not likely to add SendPulse support in Anymail myself. But I'm open to a PR if someone else wants to do the work.

Incidentally, you should be able to use SendPulse with Django today, without needing an Anymail integration. Django's default EmailBackend supports SMTP. See Django's [*Sending Email*](https://docs.djangoproject.com/en/stable/topics/email/) docs. The settings you'll need for `EMAIL_HOST`, `EMAIL_HOST_PASSWORD`, etc. should be in your [SendPulse SMTP settings](https://sendpulse.com/knowledge-base/smtp/sendpulse-smtp-send-emails#copy-your-smtp-login-credentials).

(Also, if three other ESPs have already suspended you, it might be a good idea to first figure out what's problematic about the content you're sending or the addresses you're sending it to. If a lot of recipients are mashing the spam button, you're going to quickly get banned at any legitimate ESP, no matter how well you try to explain your business to them.)
