### ISSUE TITLE
Add support to Resend.com

### ISSUE THREAD

**Issue by arsaizdihar** [anymail/django-anymail#329]
It would be helpful to add API support to [Resend](https://resend.com/)

**Comment by medmunds** [comment]
Resend seems like a good fit for Anymail:
- Has a [transactional sending API](https://resend.com/docs/api-reference/emails/send-email)
- Supports [event tracking webhooks](https://resend.com/docs/dashboard/webhooks/introduction)
- Has a free tier which Anymail could use for development and regular integration testing

A PR would be welcome if anyone is interested, or I can probably take a look in a few weeks.

Additional notes on feature mapping…

As far as I can tell, Resend does not support ESP-stored templates or merge/batch sending. (It has a React-based template feature, but I think these are rendered locally before calling the send API.)

Among [common ESP sending options](https://anymail.dev/en/stable/sending/anymail_additions/) Anymail normalizes, Resend supports only metadata (which it calls "tags")—and it's not clear whether this info is available to tracking webhooks. (Resend doesn't currently seem to support scheduled sending, overriding open/click-tracking per message, or what Anymail calls "tags".)

Resend does not currently seem to offer inbound mail.

**Comment by rez0n** [comment]
Hi @medmunds 
Sorry for bothering, any progress with Resend integration?

**Comment by medmunds** [comment]
@rez0n actually started working on it yesterday, will open a WIP PR soon. Like most ESPs, Resend's documentation isn't complete, so there have been a bunch of things to figure out.

**Comment by medmunds** [comment]
Implemented via #341, will be in the next release. 

See [docs](https://anymail.dev/en/latest/esps/resend/). Be sure to review the [limitations and quirks](https://anymail.dev/en/latest/esps/resend/#limitations-and-quirks).

**Comment by medmunds** [comment]
Resend support released in Anymail 10.2
