### ISSUE TITLE
Anymail doesn't want me to use local settings

### ISSUE THREAD

**Issue by Brachamul** [anymail/django-anymail#33]
Hello,

I usually have a settings.py file and a local_settings.py file, so that my private info like api keys aren't published when I sync my repos to github.

However, when using anymail and setting my mailgun API key in local_settings.py, I get the following error message : 
```You must set ANYMAIL_MAILGUN_API_KEY or ANYMAIL = {'MAILGUN_API_KEY': ...} or MAILGUN_API_KEY in your Django settings```

Here is the code I've been using to bring the local_settings into the settings.py file : 
```
try: from local_settings import *
except ImportError: pass
```

Is my code wrong, or does anymail have a test that my local_settings won't pass ?

**Comment by medmunds** [comment]
Anymail has no way of knowing where the settings came from -- it's all just a single django.conf.settings by the time it gets to Anymail's code.

It's impossible to say what's not working without seeing the code you're using to set Anymail settings in local_settings.py and settings.py. (And we'd also need to know whether the local_settings import is before or after any other Anymail settings you might be defining in settings.py.)

The way you're importing local_settings will overwrite any settings defined above it in settings.py. And any settings defined below that import in settings.py will overwrite the local_settings. 

If you have an `ANYMAIL = {...}` dict in both files, whichever dict comes last will *completely overwrite* the other one -- there's no magic in python's import mechanism that could merge them. (And if that's the problem, you can use the non-dict `ANYMAIL_MAILGUN_API_KEY = ...` form to work around it.)

**Comment by medmunds** [comment]
Assuming you either solved the problem or lost interest. Please reopen with additional details if this is still an issue for you.
