### ISSUE TITLE
Mailjet Open tracking?

### ISSUE THREAD

**Issue by torusservices** [anymail/django-anymail#342]
I do not see any open tracking specifically with Mailjet, on Sendinblue it works by default. But Mailjet not even on their side there doesn't seem to be any open tracking. Even tho it is enabled on the fresh account.

- Anymail version (latest)
- ESP (Mailjet)

```

from django.core.mail import send_mail, get_connection
from django.http import HttpResponse

def send_email_view(request):
   
#     You can even use multiple Anymail backends in the same app:
    mailjet_backend = get_connection('anymail.backends.mailjet.EmailBackend',)
    send_mail("",
            "",
            "",
            [""],
            connection=mailjet_backend)


    return HttpResponse("Email sent successfully!") 

```

**Comment by torusservices** [comment]
mind you delivered tracking is working

**Comment by medmunds** [comment]
Open tracking works by adding an invisible `<img>` tracking pixel to the html part of the email. If your email only includes plain text, not html, the behavior depends on your ESP. Some ESPs (like Sendinblue apparently) will convert your plain text to html, and include the tracking pixel in that. Other ESPs (like Mailjet) send a text-only message, which won't have a tracking pixel so won't generate open events.

If you want to use open or click tracking, it's best to send email that includes both html and text parts:

```python
send_mail(
    "subject", 
    "text message", 
    "from@example.com", 
    ["to@example.com"], 
    html_message="html message"  # <--
)
```

**Comment by medmunds** [comment]
@torusservices if that didn't solve your problem, please reopen with additional details to reproduce

**Comment by torusservices** [comment]
No you clarified it perfectly sorry about forgetting to reply that you helped!
