### ISSUE TITLE
Prevent Gmail from grouping same subjects Emails

### ISSUE THREAD

**Issue by alexislg2** [anymail/django-anymail#37]
Hey,
I'm using Anymail with Mailgun. My server is sending messages to my Users frquently with always same subject. This causes Gmail to group them in same thread.

Is there any solution to avoid that? It's not so clear how Gmail decides to group mails or not. For Example Amazon sends me always the same subject Email with same sender for each of my orders. But they appear in different threads for Amazon and not for me.

Any idea?

**Comment by medmunds** [comment]
This isn't really specific to Anymail. (And probably isn't specific to Mailgun.) 

You might try asking on StackOverflow (tag:gmail) or in somewhere in the official [Gmail support forum](https://productforums.google.com/forum/#!forum/gmail). Also, this is often called "email threading," so you might try searching variations of that (if you haven't already).

(FWIW, and much to my frustration, Gmail seems to randomly group Amazon's order and shipping notifications in my own inbox -- often hiding one of the tracking numbers in a "..." quoted reply section.)
