### ISSUE TITLE
Mailjet inline attachments require a "not empty" filname

### ISSUE THREAD

**Issue by chickahoona** [anymail/django-anymail#407]
There is currently this code here in the Mailjet integration:

https://github.com/anymail/django-anymail/blob/79aec15784d8a18e2004a09f66bd62749c06d8fa/anymail/backends/mailjet.py#L198

When I run this code below:

```python
msg = EmailMultiAlternatives('test', 'test_msg_plan', 'from@example.com',
                             ['to@gmail.com'])

msg.attach_alternative(msg_html, "text/html")
msg.mixed_subtype = 'related'


fp = open(os.path.join(os.path.dirname(__file__), '..', '..', 'static', 'email', 'logo.png'), 'rb')

msg_img = MIMEImage(fp.read())
fp.close()
msg_img.add_header('Content-ID', '<{}>'.format(f))
# msg_img.add_header('Content-Disposition', 'inline', filename='logo.png')
msg.attach(msg_img)

msg.send()
```

I am getting this API response:

```
Mailjet API response 400 (Bad Request):
{
  "Globals": {
    "Status": "error",
    "Errors": [
      {
        "ErrorIdentifier": "21b25717-0351-43da-bdb3-6985d4dfb9d3",
        "ErrorCode": "mj-0012",
        "StatusCode": 400,
        "ErrorMessage": "Empty string not allowed.",
        "ErrorRelatedTo": [
          "InlinedAttachments[0].Filename"
        ]
      }
    ]
  }
}
```

it took me a while to find that `Content-Disposition`-line which is a way to set a filename.

My recommendation would be to fix it like below (not sure if there is a smarter way)

Before:

```python
att = {
    "ContentType": attachment.mimetype,
    "Filename": attachment.name or "",
    "Base64Content": attachment.b64content,
}
```

After:

```python
att = {
    "ContentType": attachment.mimetype,
    "Filename": attachment.name or attachment.cid or "attachment",
    "Base64Content": attachment.b64content,
}
```

**Comment by medmunds** [comment]
Thanks for the report. 

Anymail's Mailjet integration tests *do* [try an inline image](https://github.com/anymail/django-anymail/blob/45848440b3727d8236bdae8c4b2b081705d66f7a/tests/test_mailjet_integration.py#L94), but they're using Anymail's [`attach_inline_image_file()`](https://anymail.dev/en/stable/sending/anymail_additions/#anymail.message.attach_inline_image_file) helper, which passes along the filename.

Your proposed fix looks good to me. I think we should also change that line in the integration tests to `cid = message.attach_inline_image(sample_image_content())`, which won't include the filename. (And probably cover both cases in the mailjet_backend_tests.)
