### ISSUE TITLE
mandrill error with new key init

### ISSUE THREAD

**Issue by patroqueeet** [anymail/django-anymail#46]
when adding a new webhook to mandrill, it verifies my webhook url:

```
import mandrill
mandrill_client = mandrill.Mandrill('SOMEKEY')
 events = ['send', 'open', 'click']
result = mandrill_client.webhooks.add(url='https://AUTH:CODE@someurl.com/webhooks/mail/mandrill/tracking/', description='PreProd', events=events)
```

but this fails with `You must set ANYMAIL_MANDRILL_WEBHOOK_KEY or ANYMAIL = {'MANDRILL_WEBHOOK_KEY': ...} or MANDRILL_WEBHOOK_KEY in your Django settings` as I don't have the key yet.

hence, no key, no verification, no verification, no key...  hen-egg issue...

pls help!

**Comment by medmunds** [comment]
Hmm... I'm guessing this is when Mandrill tries to issue a HEAD request to the webhook, to verify that it exists. There's code in Anymail to respond "OK" to HEAD requests, without trying to validate them, but it looks like the MANDRILL_WEBHOOK_KEY setting is checked before that code is even reached.

Could you try this? In your settings.py, set the webhook key to an empty string:

```python
ANYMAIL = {'MANDRILL_WEBHOOK_KEY': "", ...}
```

and then try adding the webhook url to Mandrill again.

If that works, I'll update the docs and/or figure out a way to allow the HEAD requests through without the key set. (As noted in [the docs](http://anymail.readthedocs.io/en/latest/esps/mandrill/), I don't have testing access to Mandrill.)

**Comment by patroqueeet** [comment]
hey, that worked perfectly. I used http://www.hurl.it to check for the `HEAD` and tuned things until that worked. mandrill was an easy go afterwards. yes a quick note inside docu would be a fantastic thing though :)

thanks for the hint!

**Comment by medmunds** [comment]
Great! Thanks for tracking it down.

I'll fix this to allow the HEAD request through, and improve the Mandrill doc section.

**Comment by patroqueeet** [comment]
got to thank for the fast and precise support!
