### ISSUE TITLE
Rename all backends to "EmailBackend" for consistency with Django

### ISSUE THREAD

**Issue by medmunds** [anymail/django-anymail#49]
Django's [built-in email backend](https://docs.djangoproject.com/en/1.10/topics/email/#email-backends) class names are all `EmailBackend`; the type of backend is indicated by the module:

* django.core.mail.backends.**smtp**.EmailBackend
* django.core.mail.backends.**console**.EmailBackend
* django.core.mail.backends.**filebased**.EmailBackend
* django.core.mail.backends.**locmem**.EmailBackend
* django.core.mail.backends.**dummy**.EmailBackend

Before 1.0-alpha, Anymail should change to follow Django's naming convention:

* anymail.backends.**mailgun.MailgunBackend** → anymail.backends.**mailgun**.EmailBackend
* anymail.backends.**mandrill. MandrillBackend** → anymail.backends.**mandrill**.EmailBackend
* anymail.backends.**postmark.PostmarkBackend** → anymail.backends.**postmark**.EmailBackend
* anymail.backends.**sendgrid.SendGridBackend** → anymail.backends.**sendgrid**.EmailBackend
* anymail.backends.**sparkpost.SparkPostBackend** → anymail.backends.**sparkpost**.EmailBackend

To avoid breaking code, the current names should still be supported with a deprecation warning.

(As an additional benefit, this would eliminate the need for admonishments throughout the docs on how to properly capitalize each ESP's name.)

**Comment by areski** [comment]
This names change is a great idea. 
My 2 cents for someone using your project for the first time it was a bit confusing as https://anymail.readthedocs.io/en/latest/installation/ was telling me to use the new naming convention but that wasn't supported on the pypi version. 
It might be best that the doc point to the last official release.

Thanks for your hard work!

**Comment by medmunds** [comment]
@areski sorry for the confusion. I've changed readthedocs to default to the stable release version, and updated the links in the readme to point to those, too.

**Comment by areski** [comment]
Thanks a lot :+1:  :)
