### ISSUE TITLE
Implement ESP templates and merge vars

### ISSUE THREAD

**Issue by medmunds** [anymail/django-anymail#5]
Normalized handling for ESP templates and merge variables

**Comment by medmunds** [comment]
Would love to hear from people who are using Mandrill templates now (MailChimp or Handlebars syntax) and are planning to change ESPs. What are you planning to do about your templates? Rewrite them for another ESP? Switch to Django templates?

Merge vars are one of the tricker areas to normalize, because ESPs have different capabilities around global and per-recipient merge vars. Understanding how the Djrill community is thinking about migrating would help with the design.

**Comment by diwu1989** [comment]
we went with django templates, that's basically the only way to get all the unit testing done, can't really unit test templates that use any ESP's specific template language

**Comment by cralston0** [comment]
Ditto diwu's repsonse.

**Comment by avelis** [comment]
@medmunds Since I made #10 I can tell you what I am doing more or less. I have the special case where I need to send transactional bulk email as one API call. Therefore, we subclassed the Payload class in this library to add the methods so the backend class would set the correct fields in the SMTPAPI headers to send over to the ESP (i.e. template_id and template variables).

The method names I came up with eventually were very specific to that ESP (SendGrid). So, the challenge eventually becomes: how to support each ESP template system in their respective backends classes.

**Comment by medmunds** [comment]
Thanks for the input. I can see at least two common cases where someone might choose ESP templates over Django templates:

1. The "bulk transactional" case @avelis described above, where you want to issue a single API call to the ESP that generates multiple emails. (Usually for performance reasons.)

2. You're already using your ESP's templating for (say) marketing email, and the people who developed those templates will also develop your transactional templates. And those people know your ESP's template system, not Django's. (Or they want the ability to update the email templates more often than you want to deploy your Django project.)

In either of these cases, I think Anymail can give the ability to identify an ESP template_id and substitution/merge variables for that template. There are still a handful of differences between how ESPs handle variables, which I'll try to list in a later comment, but the general approach and simple template variables would be very portable between ESPs.

The one case this *doesn't* cover is where your Django code supplies the actual body of the template *in the ESP's template language* (rather than just an ID to a stored template already at your ESP). Some ESPs support this, others don't. But I'm leaning toward ignoring it for Anymail. We definitely don't want to get into transcoding template syntax (which I think was being discussed in #10), and if you're writing template content in your Django code, it seems like you'd be better off just using Django templates.

**Comment by medmunds** [comment]
Here's my enumeration of template/merge capabilities, by ESP:

Referring to stored template by ID:
* Mailgun: not supported? (you can only supply the template content as the message body at send time?)
* Mandrill: template_name
* PostMark: TemplateId
* SendGrid: filters: templates
* SparkPost: content: template_id

"Global" merge variables--substituted into the template for *all* recipients:
* Mailgun: not supported?
* Mandrill: message.global_merge_vars
* PostMark: TemplateModel
* SendGrid: not supported?
* SparkPost: substitution_data

"Per-recipient" merge variables--within a single send call, use different substitutions for different recipients:
* Mailgun: recipient-variables
* Mandrill: message.merge_vars
* PostMark: not supported?
* SendGrid: sub
* SparkPost: recipients: substitution_data

Still need to investigate:
* "Complex" merge variables: ability to iterate over lists (arrays) and access dict (object) properties of merge variables within the template language
* "Content blocks": ability to substitute in a section of template content at send-time, and recursively merge template variables within that substituted content

**Comment by bjesus** [comment]
I'm moving from Djrill to Anymail because of the recent Mandrill change. Not having templates is a huge pain for me - I don't mind converting my templates to SendGrid's template format, but I do mind the bandwidth I use and the time it takes to email 10,000 messages that are 99% same, but now have to be sent separately. I haven't tried it yet, but at least with Mandrill - using templates saved my application.

Using templates with Anymail (like I read [here](https://anymail.readthedocs.org/en/latest/sending/templates/)) didn't work for me with SendGrid. It just completely ignored the template. I guess it's not supported yet, right? I'll try generating the templates locally then. Anyhow, thanks for Anymail :-)

**Comment by medmunds** [comment]
Sorry about the confusing docs, @bjesus. I thought I'd commented out all the things that aren't implemented yet, but the ESP template stuff slipped past. It's still planned for milestone 0.4 (and this issue is tracking). Given the level of interest, I may try to move ESP templates earlier, ahead of inbound email.

In the meantime, you can use Anymail's [`esp_extra`](https://anymail.readthedocs.org/en/latest/esps/sendgrid/#esp-extra-support) attribute to get SendGrid features that aren't supported directly by Anymail. For SendGrid templates, this would look something like (untested):

```python
message.esp_extra = {
    # SendGrid extensions usually go in the x-smtpapi parameter to the send API call:
    "x-smtpapi": {
        # Enable SendGrid template engine, identify template:
        "filters": {
            "templates": {
                "settings": {
                    "enable": 1,
                    "template_id": "5997fcf6-2b9f-484d-acd5-7e9a99f0dc1f"
                }
            }
        },
        # Define template substitutions, in same order as message recipients:
        "sub": {
            ":name": [
                "Alice",
                "Bob"
            ],
            ":price": [
                "$4",
                "$4"
            ]
        }
    }
}
```

Something similar could be used with other ESPs, substituting their own API parameters. `esp_extra` is intended as an "escape hatch" to get to the raw ESP API for things that Anymail doesn't yet or (for obscure features) won't ever support in the normalized code. And you can use it now to get around limitations in early releases of Anymail.

**Comment by bjesus** [comment]
Thank you so much! I ended up deciding to stay with Djrill & Mandrill until there would be native support for ESP templates in Anymail. It just seems kinda crazy to send the my newsletters using tens of thousands of different requests, and I didn't think about using `esp_extra`. Also I have quite a few places to implement that and I rather not end up with a messy code I'll probably update anyway in a few months / weeks. So I'll just keep track of Anymail status and hopefully I might even be able to contribute.

**Comment by medmunds** [comment]
Template/merge implementation underway in the [feature_templates](https://github.com/anymail/django-anymail/tree/feature_templates) branch. All four current ESPs are there.

Briefly:

```python
message.template_id = "ESP-template-name-or-id"
message.template_data = {
    "mike@example.com": {"name": "Mike", "order_number": 12345},
    "alice@example.com": {"name": "Alice", "order_number": 54321},
}
message.template_global_data = {
    "site": "Anymail Example",
}
```

[Some docs](http://anymail.readthedocs.io/en/feature_templates/sending/templates/) are also ready. (Still need to add ESP-specific notes: Postmark doesn't support batch send or per-recipient `template_data`; Mailgun doesn't support stored templates or `template_id`.)

I'm debating changing the data attribute names to `merge_data` and `merge_global_data` (or `merge_defaults`), since merging is often available independently of using ESP stored templates.

Also, I'm considering a few additions to the SendGrid implementation. SendGrid's API wants you to include merge variable delimiters in your merge data keys. That is, where for other ESPs you'd specify merge data as `{'name': "Mike", 'order_number': 12345}`, with SendGrid you'd need to use `{'%name%': "Mike", '%order_number%': 12345}` (if you're using `%` to mark merge vars in your template). 

That makes SendGrid's merge feature flexible -- you can use whatever template variable syntax you want -- and simple for them to implement (just simple string replacement). But I suspect it will be error-prone in Anymail, particularly if you're switching between ESPs. I'm thinking about adding a warning in the SendGrid backend if you try to use merge variable names without any delimiters, and/or a setting that automatically adds your choice of delimiters to the names.
