### ISSUE TITLE
Normalizing Mandrill's soft_bounce Status

### ISSUE THREAD

**Issue by JustinNazari** [anymail/django-anymail#56]
Anymail currently [normalizes Mandrill's 'soft_bounce' status to 'deferred'](https://github.com/anymail/django-anymail/blob/master/anymail/webhooks/mandrill.py#L84). The [Anymail documentation defines](http://anymail.readthedocs.io/en/stable/sending/tracking/#normalized-tracking-event) the normalized 'deferred' status as "...the ESP will keep trying to deliver the message, and should generate a separate bounced event if later it gives up." However, according to [Mandrill's documentation](https://mandrill.zendesk.com/hc/en-us/articles/205582937-About-Bounces), Mandrill does not attempt to redeliver either a 'hard_bounce' or 'soft_bounce': "After a bounce occurs for a recipient email address, Mandrill stops attempting delivery of the email. Further email to that address will be rejected temporarily." 

I propose that Mandrill's 'soft_bounce' status be normalized to 'bounced' to be consistent with both Mandrill's and Anymail's documentation.

**Comment by medmunds** [comment]
Thanks. Postmark soft bounces were also being incorrectly normalized to "deferred." Changing both.
