### ISSUE TITLE
What Django versions should Anymail support?

### ISSUE THREAD

**Issue by medmunds** [anymail/django-anymail#6]
Right now, Anymail is only building on Django 1.8 and 1.9.

Most of the code (from Djrill) is still compatible all the way back to Django 1.4. There are a few tests that are using some newer timezone pieces.

If it's important for people migrating from Djrill, it wouldn't be too hard to maintain compatibility with older Django versions.

But if everyone's already on Django 1.8 or later, that effort could probably be better spent elsewhere.

**Comment by diwu1989** [comment]
1.8+ only please, because the previous LTS version is going to die out soon, and anyone serious about Django should be either continuously upgrading to the latest version, or staying put at the LTS
![image](https://cloud.githubusercontent.com/assets/380950/13739727/1864e81c-e98a-11e5-87ad-f103326c300f.png)

**Comment by medmunds** [comment]
Django 1.8 and above it is, for now.

I'd like to aim Anymail's future policy at supporting:
* all Django versions [supported by the Django Foundation](https://www.djangoproject.com/download/#supported-versions)
* plus (to the extent possible) any *no-longer-supported* Django versions 
  *above a still-supported* Django LTS release. For example, in April 2017,
  Django will drop support for 1.9. But Django 1.8 LTS will still be supported, so Anymail
  should aim to continue supporting 1.9 (and 1.10) until 1.8 support is dropped in
  April 2018.
* plus upcoming Django versions as soon as possible after a beta is available

The second point is because I find it annoying when a relatively-minor package like Anymail becomes the forcing function for a project to update major packages like Django. Yes, Django may have dropped support for the version you're using, but until there's a security issue or something else that convinces you to update Django, packages like Anymail shouldn't be forcing your hand. (There are lots of other good reasons you should get onto a Django LTS release. But it's not Anymail's place to advocate for that.) (It's possible I've been spending too much time wrestling with npm dependencies lately. :smile:)

And the third point is because I find it annoying when a package *prevents* a project from updating Django as soon as a new release is available. (Thus the desire to start support as soon as possible after the beta.)
