### ISSUE TITLE
Support for OSS Postal mail service

### ISSUE THREAD

**Issue by avelis** [anymail/django-anymail#63]
[postal](https://github.com/atech/postal) recently was made available on Github as an OSS alternative to Mailgun & Sendgrid.

Supporting a new mail service backend isn't a small undertaking and could have potential challenges. However, the idea sounds really cool in concept to see a full OSS stack for mail delivery available.

**Comment by medmunds** [comment]
Postal looks really interesting, and is a great contribution to the open source community.

I don't personally have the bandwidth to set up and maintain a Postal server for development/testing with Anymail. (Though as always, contributors welcome.) It looks like Postal is the open-source version of aTech Media's own [AppMail](https://appmail.io/) ESP, so it's possible that adding AppMail support to Anymail would also cover Postal.

Anyone else wanting either Postal or AppMail support in Anymail, please help prioritize by using GitHub's "thumbs up" [reaction](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to vote for this issue.

**Comment by medmunds** [comment]
There doesn't seem to be much interest in Postal at this point. (And it looks like aTech has discontinued their hosted AppMail Postal service, so that's no longer an option.)

I'm going to close this for now. Can re-open in the future if it starts getting some upvotes.
