### ISSUE TITLE
Support for Mailchimp's Mandrill service

### ISSUE THREAD

**Issue by Skyross** [anymail/django-anymail#64]
Would be great to add support for Mandrill. Here is a basic usage of it [in official docs](https://mandrillapp.com/api/docs/messages.python.html). Anyway, I'm planning to add PR but I'm not sure about the time.

Thank you for package!

**Comment by medmunds** [comment]
You mean, [like this](https://anymail.readthedocs.io/en/stable/esps/mandrill/)? :smile:

Technically, Mandrill was the first ESP that Anymail supported, from its roots in the Mandrill-specific [Djrill](https://github.com/brack3t/djrill) package. I don't give Mandrill headline billing in Anymail's short description, because [MailChimp's opposition to "testing or developing integrated services" for Mandrill](https://github.com/brack3t/Djrill/issues/111) prevents me from fully supporting the integration. But Mandrill support is included and we do have some people using it through Anymail.

**Comment by bartmika** [comment]
Hi @medmunds,

Thank you for your work in `Djrill` and integrating it into this library. I have a request pertaining to this ticket. I have taken a look in [the documentation](https://anymail.readthedocs.io/en/stable/esps/mandrill/#) and I have had no luck getting `django-anymail` to send through `mandrill`. I am using the templates on `mandrill` side and inputted variables but am receiving a `All message recipients were rejected or invalid`.

Would it be possible if yourself or someone either (1) provide a snippet of an example code which works into this ticket or (2) updates the documentation to provide an example pertaining to this?

Thank you!

**Comment by medmunds** [comment]
@bartmika sorry Mandrill templates aren't working for you. As you probably noticed in the docs, I don't have (and MailChimp won't provide) a Mandrill account, so I can't test things myself. 

There's a [Mandrill example with inline templates](https://anymail.readthedocs.io/en/stable/esps/mandrill/#batch-sending-merge-and-esp-templates) in the docs. (You'd need to change to real, non-example recipient addresses.)

"All message recipients were rejected or invalid" means Mandrill rejected the recipient (to) address(es) for your message*. That can occur if you're sending to invalid addresses, \@example.com addresses, or (I think with Mandrill) previously-bounced or spam-report addresses. Here's more info on [refused recipients](https://anymail.readthedocs.io/en/stable/sending/django_email/#recipients-refused). Printing your `message.anymail_status.esp_response` after the failed send may provide more details.

Or look for your send in Mandrill's API logs (used to be [in their dashboard here](https://mandrillapp.com/settings/api)) to see if there's more information on why it failed.

Also, are you saying that a regular (non-template) send to the same recipient works, but you get this error when you start using a Mandrill template? If so, it would be really helpful to see the difference in code. (Or if you haven't tried a non-template send yet, it might be easier to start with that and then add templates after you're sure the basics are working.)

Finally, if none of that helps, there's additional [troubleshooting](https://anymail.readthedocs.io/en/stable/help/) info in the docs. You might also want to ask a specific question on StackOverflow, tagged "Mandrill" to get the attention of the wider Mandrill crowd (most of whom don't monitor Anymail issues).

__

\* Another possibility is always that Mandrill changed their API, and Anymail hasn't caught up. But I'd probably check the other stuff first.
