### ISSUE TITLE
Support for MailJet

### ISSUE THREAD

**Issue by dhrp** [anymail/django-anymail#65]
I see already a couple of other back-ends were requested, but I would love to see [mailjet](https://www.mailjet.com/) integrated. I think mailjet has at least one benefit over most, if not all, others, which is that the templating engine is full-featured and (reasonably) intuitive. On review sites is usually mentioned in the top 7 with transactional e-mail.

I'll look into what it will take to make an implementation myself. -- I also know that [kidig/django-mailjet](https://github.com/kidig/django-mailjet) exists, but seems to miss features. I've been having a hard time settling on a choice (is mailjet reliable enough?) that I would prefer to be able to switch fast.

**Comment by dhrp** [comment]
Just noticed that @calvin started working on a fork for Mailjet! [calvin/django-anymail](/calvin/django-anymail) I'll check out his branch.

**Comment by medmunds** [comment]
@Lekensteyn has moved @calvin's Mailjet implementation forward quite a bit. Check PR #53 for the current state.

**Comment by lorddaedra** [comment]
Check https://github.com/mailjet/mailjet-apiv3-python

**Comment by Lekensteyn** [comment]
@lorddaedra Mailjet's Python API is just a thin interface to their REST API, it does not integrate in anymail (and would thus require rewriting parts if you switch to a different provider at a later moment).

**Comment by lorddaedra** [comment]
@Lekensteyn I mean, it's official library with support, I feel, better to require official libraries (if they exists) and improve them (send PR's) than repeat them in unofficial packages, unix way etc. Just my opinion.

**Comment by medmunds** [comment]
Tasks:
* [X] Implement backend (PR #66)
* [ ] Implement webhooks
* [ ] Docs

**Comment by medmunds** [comment]
Will be released in 0.11
