### ISSUE TITLE
1.0 Release Date ETA?

### ISSUE THREAD

**Issue by jhancia** [anymail/django-anymail#68]
Appreciate this library very much and looking to use it in a new production site.  Any estimate for the 1.0 release date?

**Comment by medmunds** [comment]
There's probably no good reason not to just promote it to 1.0 sometime soon. I wanted to get enough real-world testing in place to avoid the potential for a lot of breaking changes (and full version bumps, under semver) before calling it 1.0.

I'm going to do a release in the next week or so to add Mailjet; if that's stable, can probably call it "1.0"  a few weeks later.

(FWIW, I've been using this package in production for over a year now, and I believe there are several other people doing the same. But I do understand there are cases where the "pre-release" label would be problematic.)

**Comment by medmunds** [comment]
I've just published a 1.0 release candidate to PyPI. I'll give it a few days to make sure nothing obvious is broken, and then we can call it 1.0 for real.

**Comment by medmunds** [comment]
v1.0 is live on PyPI.
