### ISSUE TITLE
Handle non-int esp codes

### ISSUE THREAD

**Issue by tomfa** [anymail/django-anymail#70]
Seems like there's an assumption that `esp_event['code']` are integers. They don't have to be. Below an error caused by a [550 5.1.1](https://www.massmailsoftware.com/smtp/550-5-1-1.php), due to a bogus email-address

![esp 5 1 1](https://user-images.githubusercontent.com/1502702/28017481-ba599f3e-6579-11e7-810a-06886ba6e165.png)

**Comment by medmunds** [comment]
I think this is the same as #62, which is fixed on master but hasn't been released yet. (Will push a release shortly, just finishing up Mailjet support first.)

**Comment by medmunds** [comment]
Actually, this had been fixed in Anymail v0.10, which was released on May 22. What version of Anymail are you using?

**Comment by tomfa** [comment]
I was running an old version, sorry. Will say hi again if updating doesn't do the trick.
Thanks a bunch for the library, Mike! 😄
