### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by fcpauldiaz** [anymail/django-anymail#73]
How do I configure anymail to send servers errors via email? I tried with Debug = False and with the Admin config but no luck
```
ADMINS = [('John', 'john@example.com'), ('Mary', 'mary@example.com')]
````

**Comment by ygwain** [comment]
I believe it's not Anymail problem. Try to set `settings.SERVER_EMAIL` to something different than Django's default `root@localhost`. Maybe it's not your case but who knows :)
