### ISSUE TITLE
Mailgun: Metadata is not available in opened or clicked events

### ISSUE THREAD

**Issue by gertsteyn** [anymail/django-anymail#76]
Mailgun now strips the X-Mailgun-Variables header from the **message-headers** field for clicked/opened and possibly other events. (Strangely not for delivered)

There is now a **user-variables** dictionary that contains the meta data.

**Comment by gertsteyn** [comment]
So it seems **user-variables** is only shown in their log.

The source code comment: "_Mailgun merges metadata fields with the other event fields._" is still true

BUT _"However, it also includes the original message headers which have the metadata separately as X-Mailgun-Variables._" is not true for opened and clicked events, for some reason they strip the X-Mailgun-Variables header!

**Comment by medmunds** [comment]
Mailgun's approach of [merging "custom variables"](http://mailgun-documentation.readthedocs.io/en/latest/user_manual.html#attaching-data-to-messages) directly into the posted event is really... inconvenient. Among other issues, it means you must avoid choosing custom variable names that could conflict with any current *or future* Mailgun tracking event properties if you want to access those variables from a webhook.

I'm starting to think the only way for Anymail to (semi-)reliably recover metadata (custom user-variables) from a Mailgun tracking event is to just include *all* event data that doesn't match a known Mailgun property. It'll be a little fragile -- if/when Mailgun adds new event properties, Anymail will think those are metadata until it's updated. I'll look at making that change.

A useful Mailgun feature request would be for them to include the 'user-variables' event property in the fields posted to tracking webhooks. (user-variables is available through their [events API](http://mailgun-documentation.readthedocs.io/en/latest/api-events.html#event-structure); it's just not posted to the webhooks in un-merged form.)

**Comment by medmunds** [comment]
BTW, a workaround in your event hook is to access the raw Mailgun [esp_event](https://anymail.readthedocs.io/en/stable/sending/tracking/#anymail.signals.AnymailTrackingEvent.esp_event) fields directly. If your metadata field is named "user1", the value will be available in a Mailgun tracking webhook as `event.esp_event["user1"]`.

(This won't be portable if you ever switch ESPs, of course.)
