### ISSUE TITLE
Asynchronously send emails by overriding EmailBackend?

### ISSUE THREAD

**Issue by mistalaba** [anymail/django-anymail#79]
Hi! 
Thanks for an excellent product!

I had this idea to override the Emailbackend so that self.send_messages or self._send(message) would be handled by a Celery task instead. Has anyone done something similar or am I approaching this wrong?

Thank you, and sorry if this is not the proper place to ask a question. I would post this in a more appropriate place if I knew where.

**Comment by medmunds** [comment]
Glad you're finding Anymail useful.

Yes, if you want to send messages asynchronously (and you [probably do](https://anymail.readthedocs.io/en/stable/tips/transient_errors/)), overriding Django's EmailBackend with one that queues up messages for a separate task is a great way to add that functionality.

There's at least one Django EmailBackend package out there that implements async sending with Celery: [django-celery-email](https://pypi.python.org/pypi/django-celery-email). You should be able to point its CELERY_EMAIL_BACKEND setting to an Anymail backend to use the two together. (But I haven't tested it myself—let me know if you do and I'll add it to the Anymail docs.)

**Comment by mistalaba** [comment]
Thanks @medmunds! I found that app too, but couldn't get it to work. I finally came up with the following (hacky-ish) solution:
```
# backends.py
from anymail.backends.mailgun import EmailBackend
from .tasks import async_send_messages

class CustomEmailBackend(EmailBackend):
    def send_messages(self, email_messages):
        async_send_messages.delay(email_messages)
```

```
# tasks.py:
@app.task()
def async_send_messages(email_messages):
    conn = get_connection(backend='anymail.backends.mailgun.EmailBackend')
    conn.send_messages(email_messages)
```

If there's a better way, please let me know!

**Comment by medmunds** [comment]
That's the right idea. Your CustomEmailBackend should just subclass Django's BaseEmailBackend directly, and it needs to return the number of messages "delivered" (queued). Something like:

```python
from django.core.mail.backends.base import BaseEmailBackend
from .tasks import async_send_messages

class CustomEmailBackend(BaseEmailBackend):
    def send_messages(self, email_messages):
        async_send_messages.delay(email_messages)
        return len(email_messages)
```

See Django's (brief) docs on [defining custom email backends](https://docs.djangoproject.com/en/stable/topics/email/#defining-a-custom-email-backend).

Also, you should plan for your `async_send_messages` task to occasionally fail -- ESPs have API downtime, network routes develop temporary glitches, etc. You can probably use something like Celery's [`Task.retry`](http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.retry) to gracefully handle [`AnymailAPIError`](https://anymail.readthedocs.io/en/stable/sending/exceptions/#anymail.exceptions.AnymailAPIError) exceptions.

**Comment by medmunds** [comment]
Ah, so just took a closer look at [django-celery-email](https://pypi.python.org/pypi/django-celery-email). Although it *should* work with an Anymail backend in its CELERY_EMAIL_BACKEND setting, by default only the standard Django EmailMessage attributes will make it through. Anymail's custom attributes like `tags` or `template_id` will be lost. The release notes mention a CELERY_EMAIL_MESSAGE_EXTRA_ATTRIBUTES setting that could be used to work around this: set it to a list of Anymail attribute names you use. 

[django-celery-email [manually serializes](https://github.com/pmclanahan/django-celery-email/blob/2.0.0/djcelery_email/backends.py#L15) the EmailMessage objects for the Celery task params, and its [custom serializer](https://github.com/pmclanahan/django-celery-email/blob/2.0.0/djcelery_email/utils.py#L26-L68) only handles known attributes by default. Also, django-celery-mail currently has some [open issues](https://github.com/pmclanahan/django-celery-email/issues/46) around serializing inline attachments and possibly multipart alternatives.]

Speaking of which, if you're on Celery 4.0 or later, your CustomEmailBackend will also need to serialize the email_messages parameter for Celery. [Celery 4's default JSON serialization](http://docs.celeryproject.org/en/latest/userguide/calling.html#calling-serializers) won't handle a Django EmailMessage. The simplest solution would probably be to let Celery do all the work with the `pickle` serializer (which was the default in earlier Celery releases). Pickle can handle a complete EmailMessage object including all custom Anymail additions. Just be aware of potential [security concerns with pickle](http://docs.celeryproject.org/en/latest/userguide/security.html#serializers) if you construct EmailMessages from unsanitized user-supplied content.

Put it all together, and you get something like:

```python
# tasks.py: [UNTESTED CODE]
@app.task(
    autoretry_for=(AnymailAPIError,), retry_backoff=True,  # deal with network glitches
    serializer="pickle")  # handle a list of EmailMessage objects in the param
def async_send_messages(email_messages):
    conn = get_connection(backend='anymail.backends.mailgun.EmailBackend')
    conn.send_messages(email_messages)
```

**Comment by mistalaba** [comment]
Thanks for your detailed analysis, help and tips! 

I think the reason I didn't get django-celery-email to play nice with django-anymail was that my celery setup was wrong at the time, but either way, it seems overkill to use that extra package when doing these small changes is sufficient (including your corrections, of course!).

Thanks again for your hard work!

**Comment by sfdye** [comment]
Thanks for the post, it is very informational.

Sorry if this is a silly question, what is the general best practice to send email asynchronously, without vendor lock-in. Say I am using `django-anymail` in my project, is it already sending emails asynchronosly? or I have to integrate it with something like 'django-celery-email`?

**Comment by medmunds** [comment]
@sfdye django-anymail does *not* by itself send emails asynchronously (in the background or on a separate thread from the calling code). If you are sending emails from a Django view -- in response to a user action -- then best practice is to move the send off of the main thread, so that you don't delay the response to the user if the Email Service Provider's send API takes a long time.

Different Django projects have different approaches to async task scheduling, so django-anymail doesn't include any async code of its own. Celery is very popular with Django; if you're already using it in your project for other reasons, it's a good choice for email, too. You can combine Celery with Anymail using the code discussed in this issue, or by using the [django-celery-email](https://pypi.python.org/pypi/django-celery-email) package.

Another background task manager for Django is [django-channels](https://channels.readthedocs.io/en/latest/).

If you're not using Celery or Channels, a simpler way to go async might be [django-mailer](https://pypi.python.org/pypi/django-mailer). It uses your existing Django database to manage the send queue, and you set up a cron job to periodically process the queue from a separate process.

Your async sending code can also handle any errors from calling the ESP's API. There's a bit more discussion of this in the [Anymail docs](https://anymail.readthedocs.io/en/stable/tips/transient_errors/).

**Comment by sfdye** [comment]
@medmunds Thank you so much for the great explanation. It deserves to be in the docs!
