### ISSUE TITLE
Add pre- and post-send signals

### ISSUE THREAD

**Issue by medmunds** [anymail/django-anymail#8]
In BaseBackend, send two signals around outbound messages:

1. pre-send: after the payload is constructed, but before the send.
  Gives receivers a chance to cancel the send (e.g., to implement
  blacklists) or otherwise muck with the payload, or to log a
  sent-message model (e.g., for an email tracking dashboard)

2. post-send: with the normalized response (including message id).
  Good place to (e.g.,) update your sent-message model with the
  message id.

**Comment by diwu1989** [comment]
this sounds useful, right now, we subclass the email backend to do email gating and blacklisting type of things, signal would make that process cleaner
