### ISSUE TITLE
Console or dummy backend for testing

### ISSUE THREAD

**Issue by yourcelf** [anymail/django-anymail#85]
Feature request: Anymail provides several extensions to stock behavior such as setting `msg.anymail_status` after send,  and firing pre- and post-send signals, none of which happen when using  `django.core.mail.backends.console.EmailBackend`.  As a result, it's difficult to write integration tests for the behavior of signal handlers and status processing code.

A dummy or console backend which at a minimum provides `anymail_status` after send and fires off appropriate pre/post send hooks would make testing code that leverages those features much easier.

**Comment by medmunds** [comment]
Have you tried Anymail's [`test.EmailBackend`](https://anymail.readthedocs.io/en/stable/tips/test_backend/)? It should set the message status and trigger send signals, and has some other features that can be useful for email testing.

**Comment by yourcelf** [comment]
I'd missed that, thanks!  That gets me part of the way there.  For test cases that only create a single message in between database resets, it works fine, but I'm getting blocked by the hard-coded `message_id=1`, which results in unique constraint violations for my send handler which stores message ID's of outgoing messages as an identifier for associating with tracking events.

It would also still be useful to see console output of messages on localhost during development; so I could see a value of a backend that solved both of those issues.

If I find a moment and you're open to the idea, I'll work up a PR.

**Comment by medmunds** [comment]
It would certainly make sense for the test EmailBackend to generate a unique message_id for each recipient. PR welcome.

I'm also open to the idea of a separate console backend. (If you find this is replicating a lot of code from the existing test backend, feel free to refactor to share code if that seems cleaner.) 

BTW, there's an undocumented test EmailBackend feature where you can [set `anymail_test_response`](https://github.com/anymail/django-anymail/blob/v1.2/anymail/backends/test.py#L37-L47) on a message, either to a dict with a `"recipient_status"` key mapping recipient email to `AnymailStatus` ([example](https://github.com/anymail/django-anymail/blob/v1.2/tests/test_send_signals.py#L103-L107)), or to an `AnymailAPIError` instance to simulate a failure. This probably isn't all that useful for your integration tests, but can be helpful for email unit tests.

**Comment by medmunds** [comment]
Released in v1.3. Thanks again!
