### ISSUE TITLE
Allow different `MAIL FROM` or `Return-Path` and `From` headers.

### ISSUE THREAD

**Issue by YPCrumble** [anymail/django-anymail#91]
Thanks for writing this great library!

I'm using Anymail 1.3, python-sparkpost 1.3.5, and Django 2.0.2. 

I've also raised this issue on https://github.com/SparkPost/python-sparkpost/issues/161 but I'm starting to think this issue is better suited to Django-Anymail.

The issue is in trying to create a bounce domain for emails. [Django's solution](https://code.djangoproject.com/ticket/9214) can be seen [here in the codebase](https://github.com/django/django/blob/a38ae914d89809aed6d79337b74a8b31b6d3849a/django/core/mail/message.py#L256). 

To create a custom bounce domain, one puts the bounce domain in the `from_email` parameter, and a custom `From` header for the message's `From` address. This way you can send an email with a custom `Return-Path` header like mail@bounces.example.com and have the message's `From` header be something else like inbox@example.com. 

Because this is a Django library, my suggestion is to follow Django's standard in checking for a custom `From` header before setting the `from_email`. This way one can switch to/from vanilla Django to Django-Anymail without having to rewrite EmailMultiAlternatives.

Happy to create a PR if this makes sense/would be helpful?

**Comment by medmunds** [comment]
Interesting.

So, first a workaround: [SparkPost's transmissions API](https://developers.sparkpost.com/api/transmissions.html#transmissions-samples) has a `return_path` parameter for specifying the envelope sender. In Anymail, you can set that using `message.esp_extra = {'return_path': "mail@bounces.example.com"}`. (It's not currently documented in SparkPost's Python library, but it [seems to be](https://github.com/SparkPost/python-sparkpost/blob/v1.3.5/sparkpost/transmissions.py#L34) implemented.)

That said, I agree Anymail should try to handle this the same as Django's SMTP EmailBackend, at least for portability. (It's sadly not a particularly obvious way to control this, and doesn't seem to be documented anywhere outside that bug report.)

If I'm understanding correctly, the logic is, if `message.extra_headers["From"]` is set, then:
1. Use the extra_headers value as the From address (the Django code you linked above)
2. *And also* use `message.from_email` as the envelope sender (a.k.a. SMTP FROM). Django's code for this part is hiding out [in the SMTP EmailBackend](https://github.com/django/django/blob/a38ae914d89809aed6d79337b74a8b31b6d3849a/django/core/mail/backends/smtp.py#L122-L126).

The first part should be pretty straightforward to implement in Anymail's BasePayload. The second is ESP-specific: each ESP backend will need to pass envelope_sender to the API if supported:
* SparkPost has a `return_path` API param
* Mandrill has a `["message"]["return_path_domain"]` API param
* Mailjet has a `Sender` API param
* Mailgun requires the sender domain in its API URL (and Anymail actually invented [esp_extra sender_domain](https://anymail.readthedocs.io/en/stable/esps/mailgun/#email-sender-domain) to control this)
* Postmark doesn't allow specifying the Return-Path on an individual message; you can instead set up a custom Return-Path tied to the From email (or domain) at the time you validate it as a sender.
* SendGrid maybe doesn't support using a custom Return-Path? (Quick search didn't turn up any info.)

PR welcome.

**Comment by YPCrumble** [comment]
@medmunds thanks so much for this! Update - I was about to respond to you right away but I had posted [this message](https://groups.google.com/forum/#!topic/django-developers/5p1J_A1bK9M) to the Django Developer forum. I had wanted to link it to my response but it took ages for me to get approved on that forum and it wasn't public until I was approved.

Given that you've updated this library to match Django's idiosyncrasy (thank you!!!) I think I'll add the "note" block as referenced in the Django Developers ticket. Let me know if you think differently?

**Comment by medmunds** [comment]
@YPCrumble I think adding a note to Django's EmailMessage docs would be great. Once that's accepted, I can update Anymail's docs to reference that rather than the Trac issue. It might be helpful to note that the from_email/extra_headers["From"] approach is very specific to Django's SMTP EmailBackend, so may not be supported by other backends.

Also, I'm guessing the folks at SparkPost would welcome a PR to document their return_path param for python-sparkpost.

Thanks for researching this. I wasn't aware Django's SMTP EmailBackend had this feature until you pointed to it in the code. And while looking into it I found a couple of other discrepancies that I'm addressing in Anymail.
