### ISSUE TITLE
Deprecation: 'async' and 'await' will become reserved keywords in Python 3.7

### ISSUE THREAD

**Issue by RignonNoel** [anymail/django-anymail#92]
I just want to report a futur deprecation

* Anymail version
Release 1.4

* ESP (Mailgun, SendGrid, etc.)
Mandrill but it's a generic problem.

* Versions of Django, requests, python
Python 3.7

* Exact error message and/or stack trace
```
[personal_path]/django-anymail/tests/test_mandrill_djrill_features.py:16: DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7
  self.message.async = True
```

```
[personal_path]/django-anymail/anymail/backends/mandrill.py:255: DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7
  def set_async(self, async):
```

**Comment by medmunds** [comment]
Thanks, yeah. That `async` message attr is a holdover for [Djrill compatibility](https://djrill.readthedocs.io/en/latest/usage/sending_mail/#async), so it only applies to the Mandrill backend. In Anymail, the [recommended way](https://anymail.readthedocs.io/en/stable/esps/mandrill/#changes-to-emailmessage-attributes) to set Mandrill's async option is `message.esp_extra = {'async': True}`.

I'd eventually like to get rid of that Djrill compatibility layer at some point (or maybe move it to a separate "mandrill_drjill_compatibility.EmailBackend"). 

For now, a simple fix would be to rename the parameter in the backend setter (e.g., `def set_async(self, value)`), and change the test case to use `setattr(self.message, 'async', True)` for Python 3.7 compatibility.

Django won't support Python 3.7 until Django 2.1, which is scheduled to alpha in May. (Python 3.7 is in early beta now.) So this isn't urgent to fix, but should probably get cleaned up in the next month or two.
