### ISSUE TITLE
Any way to mock?

### ISSUE THREAD

**Issue by benderTheCrime** [anymail/django-anymail#94]
* Anymail version: all of them
* ESP (Mailgun, SendGrid, etc.): any of them

Is there any way to mock emails for local development?

**Comment by benderTheCrime** [comment]
You know what? Sorry for raising, I realize that I could have just gone to check out the backends myself. Sure enough, there is a "console" and a "test" backend.

**Comment by medmunds** [comment]
Glad you found them. The [test backend](https://anymail.readthedocs.io/en/stable/tips/test_backend/) is also covered briefly in the docs.
